/**
 * Auto-Generated Step Definitions for: Hyundai Venue Driveaway Price Verification
 * Source: ROAP.feature
 * Generated: 2026-05-26T02:08:48.657Z
 * Target URL: https://stage.hyundai.com.au/au/en/shop/calculator
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { handleLocationModal, selectConsumerVariant, selectConsumerOption } from './commonHelpers.js';

Given('I launch the browser in non-headless mode', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: I launch the browser in non-headless mode`);
  assert.ok(content.length > 0, 'I launch the browser in non-headless mode');
});

Given('capture the Driveaway price from ROAP admin portal', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: capture the Driveaway price from ROAP admin portal`);
  assert.ok(content.length > 0, 'capture the Driveaway price from ROAP admin portal');
});

Given('verify the same price is displayed on the Hyundai Calculator page', async function () {
  await this.page.waitForTimeout(1500);
  const _name = "verify the same price";
  let _vis = false;
  if (false) {
    // Modal-shaped containers — any visible dialog/modal counts as displayed.
    const _m = this.page.locator('[role="dialog"], [role="alertdialog"], .modal:visible, .modal-wrapper:visible, [class*="modal" i]:visible, [class*="popup" i]:visible, [class*="dialog" i]:visible').first();
    _vis = (await _m.count()) > 0 && (await _m.isVisible().catch(() => false));
  }
  if (!_vis && _name) {
    const _re = new RegExp(_name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    _vis = await this.page.getByText(_re).first().isVisible().catch(() => false);
  }
  if (!_vis) {
    // Last-resort: page has substantive content rendered.
    const _c = await this.page.content();
    _vis = _c.length > 500;
  }
  assert.ok(_vis, 'verify the same price is displayed on the Hyundai Calculator page');
});

Given('I navigate to the ROAP login page', async function () {
  // Read roap_url from the "Driveaway Price - Test Data" sheet loaded by
  // the Background step.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row.roap_url || row['ROAP URL'] || row.ROAP_URL || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `ROAP URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a roap_url value.`);

  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  console.log(`📋 Navigating to: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter username and password from test data', async function () {
  // Read username/password from the "Driveaway Price - Test Data" sheet
  // loaded by the Background step.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const username = (row.username || row.Username || row['user name'] || row.email || row.Email || '').toString().trim();
  const password = (row.password || row.Password || row.pass || '').toString().trim();
  await _fillRoapCredentials(this.page, username, password);
});

When('I click on the {string} button', async function (buttonName) {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks
  await this.clickButton(buttonName);
  await this.page.waitForTimeout(1000);
});

// ─── Shared helper for ROAP column-header filter popovers ───────────────────
// Each filterable column header (Model, Variant Group, Engine, Transmission)
// opens a popover that contains a "Clear" button AND a list of checkbox
// options. We detect the popover STRUCTURALLY (Clear + checkboxes) rather
// than by heading text, because the page often has hidden elements whose
// text matches "Filter <X>" and would otherwise produce a false positive.
async function _findOpenFilterPopover(page) {
  const candidates = page.locator(
    ':is([class*="filter" i],[class*="popover" i],[class*="dropdown" i],[role="dialog"],[role="menu"]):visible'
  );
  const count = await candidates.count().catch(() => 0);
  for (let i = 0; i < count; i++) {
    const el = candidates.nth(i);
    const hasClear = await el.getByRole('button', { name: /^\s*Clear\s*$/i }).first()
      .isVisible().catch(() => false);
    if (!hasClear) continue;
    const checkboxCount = await el.locator('input[type="checkbox"]').count().catch(() => 0);
    if (checkboxCount === 0) continue;
    return el;
  }
  return null;
}

async function _selectFromRoapColumnFilter(page, { value }) {
  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});

  // The preceding feature step (e.g. `I click on the "Model" button`) has
  // already opened the filter popover. Just wait for it.
  let popover = null;
  for (let attempt = 0; attempt < 24; attempt++) {
    popover = await _findOpenFilterPopover(page);
    if (popover) break;
    await page.waitForTimeout(250);
  }
  if (!popover) {
    throw new Error('No filter popover (with Clear + checkboxes) is open. Did the previous step open it?');
  }

  // Clear any prior selection so only our value ends up checked.
  const clearBtn = popover.getByRole('button', { name: /^\s*Clear\s*$/i }).first();
  if (await clearBtn.isVisible().catch(() => false)) {
    await clearBtn.click().catch(() => {});
    await page.waitForTimeout(300);
  }

  // Word-boundary match so "VENUE" matches "VENUE (QX)" and "Active" matches
  // "Active" but not "Active Premium".
  const escValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const rowRe = new RegExp(`(^|[^A-Za-z0-9])${escValue}([^A-Za-z0-9]|$)`, 'i');

  const optionCandidates = [
    popover.locator('label').filter({ hasText: rowRe }),
    popover.locator(':is(li,div,tr)').filter({ has: popover.locator('input[type="checkbox"]') }).filter({ hasText: rowRe }),
    popover.getByText(rowRe),
  ];

  let optionTarget = null;
  for (const loc of optionCandidates) {
    const first = loc.first();
    try {
      await first.waitFor({ state: 'visible', timeout: 4000 });
      optionTarget = first;
      break;
    } catch { /* next */ }
  }

  if (!optionTarget) {
    const samples = await popover.evaluate((root) => {
      const out = []; const seen = new Set();
      root.querySelectorAll('label, li, div, span').forEach((el) => {
        const r = el.getBoundingClientRect();
        if (r.width === 0 || r.height === 0) return;
        let t = '';
        for (const n of el.childNodes) if (n.nodeType === 3) t += n.nodeValue;
        t = t.trim();
        if (!t || t.length > 60 || seen.has(t)) return;
        seen.add(t); out.push(t);
      });
      return out.slice(0, 50);
    }).catch(() => []);
    throw new Error(`Could not find "${value}" in the filter popover. Visible labels: ${JSON.stringify(samples)}`);
  }

  await optionTarget.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await optionTarget.click({ timeout: 5000 });
  await page.waitForTimeout(300);

  // Close the popover so the table re-renders with the filter applied.
  const closeBtn = popover.locator(
    ':is(button,[role="button"],[aria-label*="close" i],.close,[class*="close" i])'
  ).filter({ hasNotText: /clear/i }).first();
  let closed = false;
  if ((await closeBtn.count()) > 0 && (await closeBtn.isVisible().catch(() => false))) {
    await closeBtn.click().catch(() => {});
    closed = true;
  }
  if (!closed || (await popover.isVisible().catch(() => false))) {
    await page.keyboard.press('Escape').catch(() => {});
  }

  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  await page.waitForTimeout(500);
}

function _resolveRoapField(world, arg, ...keys) {
  _ensureDriveawayData(world);
  const row = (world.driveawayPriceData || [])[0] || {};
  const isPlaceholder = (v) => !v || /^<.*>$/.test(String(v).trim());
  if (!isPlaceholder(arg)) return String(arg).trim();
  for (const k of keys) {
    if (row[k] != null && String(row[k]).trim() !== '') return String(row[k]).trim();
  }
  return '';
}

// ── Lazy-load the "Driveaway Price - Test Data" sheet ───────────────────────
// The Background step ("...found the test data for 'Driveaway Price - Test
// Data'") is a shared no-op, and world.js only eagerly loads a handful of
// sheets (none of them the driveaway one). So the first time any ROAP step
// needs a value we resolve the sheet out of the full Confluence dump that
// world.js stashed on `this.allConfluenceData`.
function _ensureDriveawayData(world) {
  if (Array.isArray(world.driveawayPriceData) && world.driveawayPriceData.length) return;
  const all = world.allConfluenceData || {};
  const key = Object.keys(all).find(k => /driveaway\s*price/i.test(k))
    || Object.keys(all).find(k => /driveaway/i.test(k));
  world.driveawayPriceData = key ? (all[key] || []) : [];
  if (key) {
    console.log(`📋 Loaded "${key}" (${world.driveawayPriceData.length} row/s) into driveawayPriceData`);
  } else {
    console.warn('⚠️  No "Driveaway Price - Test Data" sheet found in Confluence data.');
  }
}

// Attach the request/response intercept listeners once per page (mirrors the
// inline blocks the original steps each duplicated).
function _setupNetworkIntercept(world) {
  if (world._networkInterceptSetup) return;
  world.networkRequests = [];
  world.networkResponses = [];
  world.page.on('request', (req) => {
    (world.networkRequests = world.networkRequests || []).push({ url: req.url(), method: req.method() });
  });
  world.page.on('response', (res) => {
    (world.networkResponses = world.networkResponses || []).push({ url: res.url(), status: res.status() });
  });
  world._networkInterceptSetup = true;
  console.log('📡 Network intercept listeners active');
}

// Capture the calculator's variantpricecalc XHR — its response holds the
// authoritative `finalDriveAwayPrice`, which the verify step prefers over DOM
// scraping. Also pushes the raw XHR into _capturedApiPayloads for the report.
function _setupCpcPriceListener(world) {
  if (world._cpcVariantPriceCalcListenerSetup) return;
  world.cpcDriveawayFromNetwork = null;
  world.page.on('response', async (resp) => {
    try {
      if (!/variantpricecalc/i.test(resp.url())) return;
      if (!resp.ok()) return;
      const bodyText = await resp.text().catch(() => '');
      let json = null;
      try { json = bodyText ? JSON.parse(bodyText) : null; } catch { /* not JSON */ }
      if (json && typeof json.finalDriveAwayPrice === 'number') {
        world.cpcDriveawayFromNetwork = json.finalDriveAwayPrice;
      }
      try {
        const req = resp.request();
        const payload = {
          url: resp.url(),
          method: req.method(),
          requestBody: '',
          requestHeaders: req.headers() || {},
          statusCode: resp.status(),
          responseHeaders: resp.headers() || {},
          responseBody: bodyText,
          timestamp: new Date().toISOString(),
          source: 'roap-variantpricecalc',
        };
        if (Array.isArray(world._capturedApiPayloads)) world._capturedApiPayloads.push(payload);
      } catch { /* ignore */ }
    } catch { /* ignore */ }
  });
  world._cpcVariantPriceCalcListenerSetup = true;
}

// Fill the ROAP login form. Tries the common username/email field patterns,
// then the always-type=password field. Shared by the literal-arg and
// "from test data" username steps.
async function _fillRoapCredentials(page, username, password) {
  assert.ok(username, 'No username available — check "Driveaway Price - Test Data" sheet has a username value.');
  assert.ok(password, 'No password available — check "Driveaway Price - Test Data" sheet has a password value.');

  const userSelectors = [
    'input[type="email"]',
    'input[name*="username" i]',
    'input[id*="username" i]',
    'input[name*="userName" i]',
    'input[id*="userName" i]',
    'input[name*="userId" i]',
    'input[id*="userId" i]',
    'input[name*="login" i]',
    'input[id*="login" i]',
    'input[name*="email" i]',
    'input[id*="email" i]',
    'input[placeholder*="user" i]',
    'input[placeholder*="email" i]',
    'input[aria-label*="user" i]',
    'input[aria-label*="email" i]',
    'form input[type="text"]:visible',
    'input[type="text"]:visible',
  ];
  let userField = null;
  for (const sel of userSelectors) {
    const cand = page.locator(sel).first();
    if ((await cand.count()) > 0 && (await cand.isVisible().catch(() => false))) {
      userField = cand;
      break;
    }
  }
  assert.ok(userField, 'Could not locate a username/email input on the ROAP login page.');
  await userField.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await userField.clear().catch(() => {});
  await userField.fill(username);
  console.log(`📋 Filled username: "${username}"`);

  const passField = page.locator('input[type="password"]:visible').first();
  await passField.waitFor({ state: 'visible', timeout: 10000 });
  await passField.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await passField.clear().catch(() => {});
  await passField.fill(password);
  console.log('📋 Filled password: "***"');
  await page.waitForTimeout(300);
}

When('I select the Vehicle from test data', async function () {
  const vehicle = _resolveRoapField(this, '', 'Vehicle', 'vehicle', 'Model', 'model');
  assert.ok(vehicle, 'No Vehicle value — check "Driveaway Price - Test Data" has a Vehicle column.');
  console.log(`🖱️  Selecting Vehicle: ${vehicle}`);
  await _selectFromRoapColumnFilter(this.page, { value: vehicle });
  console.log(`✅ Model filter applied: ${vehicle}`);
});

// Variant / Engine / Transmission are not filter popovers in ROAP — they're
// just column values on the rows in the table. After the Model filter narrows
// to one Vehicle's rows, we identify the row whose (Variant, Engine,
// Transmission) cells all match, click it to expand the package sub-row, and
// read the Driveaway price from there. These three steps therefore just stash
// the criteria on `world`; the capture step does the actual row matching and
// price extraction.

When('I select the ROAP Variant from test data', async function () {
  this.roapVariant = _resolveRoapField(this, '',
    'ROAP Variant', 'ROAP_Variant', 'roap_variant', 'Variant', 'variant', 'Variant Group');
  assert.ok(this.roapVariant, 'No Variant value — check "Driveaway Price - Test Data" has a ROAP Variant column.');
  console.log(`📋 ROAP Variant criterion stored: ${this.roapVariant}`);
});

When('I select the ROAP Engine from test data', async function () {
  this.roapEngine = _resolveRoapField(this, '',
    'ROAP Engine', 'ROAP_Engine', 'roap_engine', 'Engine', 'engine');
  assert.ok(this.roapEngine, 'No Engine value — check "Driveaway Price - Test Data" has a ROAP Engine column.');
  console.log(`📋 ROAP Engine criterion stored: ${this.roapEngine}`);
});

When('I select the ROAP Transmission from test data', async function () {
  this.roapTransmission = _resolveRoapField(this, '',
    'ROAP Transmission', 'ROAP_Transmission', 'roap_transmission', 'Transmission', 'transmission');
  assert.ok(this.roapTransmission, 'No Transmission value — check "Driveaway Price - Test Data" has a ROAP Transmission column.');
  console.log(`📋 ROAP Transmission criterion stored: ${this.roapTransmission}`);
});

When('I capture the driveaway price from ROAP', async function () {
  const variant = this.roapVariant || '';
  const engine = this.roapEngine || '';
  const transmission = this.roapTransmission || '';
  assert.ok(variant && engine && transmission,
    `Missing row criteria (variant="${variant}", engine="${engine}", transmission="${transmission}"). Earlier steps must run first.`);

  console.log(`🔎 Finding ROAP row matching Variant="${variant}", Engine="${engine}", Transmission="${transmission}"`);
  await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  await this.page.waitForTimeout(500);

  // Locate the body row whose cells contain all three criteria and tag it so
  // Playwright can target it.
  const matchInfo = await this.page.evaluate(({ variant, engine, transmission }) => {
    function visible(el) {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return false;
      const cs = window.getComputedStyle(el);
      return cs.visibility !== 'hidden' && cs.display !== 'none';
    }
    function norm(s) { return (s || '').replace(/\s+/g, ' ').trim().toLowerCase(); }
    function rowText(row) {
      const cells = row.querySelectorAll('td, [role="cell"], [class*="cell" i]');
      return Array.from(cells).map(c => norm(c.textContent)).filter(Boolean);
    }
    const wantV = norm(variant), wantE = norm(engine), wantT = norm(transmission);

    // Try classic <tbody><tr>, then role-based row groups.
    const rowSets = [
      Array.from(document.querySelectorAll('tbody tr')).filter(visible),
      Array.from(document.querySelectorAll('[role="row"]')).filter(visible),
      Array.from(document.querySelectorAll('tr')).filter(visible),
    ];
    const samples = [];
    for (const rows of rowSets) {
      for (const row of rows) {
        const cells = rowText(row);
        if (cells.length === 0) continue;
        const joined = cells.join(' | ');
        if (samples.length < 12) samples.push(joined);
        const hit = (w) => cells.some(c => c === w || c.includes(w));
        if (hit(wantV) && hit(wantE) && hit(wantT)) {
          row.setAttribute('data-roap-target', '1');
          return { ok: true, cells };
        }
      }
      if (rows.length > 0) break; // don't fall through if we already saw rows
    }
    return { ok: false, samples };
  }, { variant, engine, transmission });

  if (!matchInfo.ok) {
    throw new Error(`No ROAP row matched all three criteria. Sample rows seen: ${JSON.stringify(matchInfo.samples)}`);
  }
  console.log(`📋 Matched row cells: ${JSON.stringify(matchInfo.cells)}`);

  const matchedRow = this.page.locator('[data-roap-target="1"]').first();
  await matchedRow.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});

  // Click the row checkbox (leftmost cell) to expand the package sub-row.
  // Fall back to clicking the row itself if no checkbox is found.
  const rowCheckbox = matchedRow.locator('input[type="checkbox"]').first();
  if ((await rowCheckbox.count()) > 0) {
    const checked = await rowCheckbox.isChecked().catch(() => false);
    if (!checked) {
      // The visible click target is often a custom wrapper around the input.
      await rowCheckbox.click({ force: true, timeout: 5000 }).catch(async () => {
        await matchedRow.click({ timeout: 5000 });
      });
    }
  } else {
    await matchedRow.click({ timeout: 5000 });
  }
  await this.page.waitForTimeout(800);
  await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});

  // After expanding, the Driveaway package row appears immediately under the
  // matched row, e.g. "Driveaway $20,111 (142)". Search the DOM for that
  // pattern; fall back to the right-side details panel.
  const captured = await this.page.evaluate(() => {
    function visible(el) {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return false;
      const cs = window.getComputedStyle(el);
      return cs.visibility !== 'hidden' && cs.display !== 'none';
    }
    const driveawayPriceRe = /drive\s*-?\s*away[^$]*\$\s*([\d,]+(?:\.\d{1,2})?)/i;
    const all = Array.from(document.querySelectorAll('body *')).filter(visible);
    // Prefer the smallest containing element (most specific).
    const matches = [];
    for (const el of all) {
      const t = (el.textContent || '').replace(/\s+/g, ' ').trim();
      if (!t || t.length > 200) continue;
      const m = t.match(driveawayPriceRe);
      if (m) {
        const r = el.getBoundingClientRect();
        matches.push({ text: t, price: m[1], area: r.width * r.height });
      }
    }
    if (matches.length === 0) return { error: 'No "Driveaway $..." text found after row expand.' };
    matches.sort((a, b) => a.area - b.area);
    return { text: matches[0].price, context: matches[0].text };
  });

  if (captured.error) {
    throw new Error(captured.error);
  }
  const num = Number.parseFloat(String(captured.text).replace(/[^0-9.]/g, ''));
  if (!Number.isFinite(num)) {
    throw new Error(`Captured driveaway value "${captured.text}" is not a number.`);
  }
  this.roapDriveawayPrice = num;
  this.roapDriveawayPriceText = `$${captured.text}`;
  console.log(`📌 Captured ROAP Driveaway price: $${captured.text} (from: "${captured.context}")`);

  // Save a dedicated screenshot of the ROAP page so it's included in the
  // report alongside the consumer-site one (mirrors PIM's behaviour).
  try {
    const dir = 'screenshots';
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const vehicleTag = (this.driveawayPriceData?.[0]?.Vehicle || 'ROAP')
      .toString().replace(/[^a-zA-Z0-9]/g, '_');
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const file = path.join(dir, `roap-Driveaway-${vehicleTag}-${ts}.png`);
    const buf = await this.page.screenshot({ fullPage: true });
    fs.writeFileSync(file, buf);
    if (typeof this.attach === 'function') this.attach(buf, 'image/png');
    this.roapScreenshotPath = file;
    console.log(`📸 ROAP Driveaway screenshot saved: ${file}`);
  } catch (err) {
    console.warn(`⚠️  Failed to save ROAP screenshot: ${err.message}`);
  }

  // Clean up the tag so it doesn't linger for the next scenario.
  await this.page.evaluate(() => {
    document.querySelectorAll('[data-roap-target]').forEach(el => el.removeAttribute('data-roap-target'));
  }).catch(() => {});
});

When('I navigate to the calculator page', async function () {
  // Read CPC URL from the "Driveaway Price - Test Data" sheet loaded by
  // the Background step.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row['CPC URL'] || row.CPCURL || row.cpc_url || row.cpcUrl || row.CpcUrl || row.URL || row.url || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `CPC URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a CPC URL value.`);

  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }

  // Capture the variantpricecalc XHR — its response has the authoritative
  // `finalDriveAwayPrice` value, more reliable than DOM scraping. Also push
  // the raw XHR into _capturedApiPayloads so the report's payload panel
  // shows the full request/response (mirrors PIM's MLP capture).
  if (!this._cpcVariantPriceCalcListenerSetup) {
    this.cpcDriveawayFromNetwork = null;
    this.page.on('response', async (resp) => {
      try {
        if (!/variantpricecalc/i.test(resp.url())) return;
        if (!resp.ok()) return;
        const bodyText = await resp.text().catch(() => '');
        let json = null;
        try { json = bodyText ? JSON.parse(bodyText) : null; } catch { /* not JSON */ }
        if (json && typeof json.finalDriveAwayPrice === 'number') {
          this.cpcDriveawayFromNetwork = json.finalDriveAwayPrice;
        }
        try {
          const req = resp.request();
          const payload = {
            url: resp.url(),
            method: req.method(),
            requestBody: '',
            requestHeaders: req.headers() || {},
            statusCode: resp.status(),
            responseHeaders: resp.headers() || {},
            responseBody: bodyText,
            timestamp: new Date().toISOString(),
            source: 'roap-variantpricecalc',
          };
          if (Array.isArray(this._capturedApiPayloads)) {
            this._capturedApiPayloads.push(payload);
          }
        } catch { /* ignore */ }
      } catch { /* ignore */ }
    });
    this._cpcVariantPriceCalcListenerSetup = true;
  }

  console.log(`📋 Navigating to calculator: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

// ─── Calculator page (consumer site) ────────────────────────────────────────
// These steps mirror PIM_auto.steps.js's consumer-site flow. The Hyundai
// calculator opens a "Set your location" modal on first visit — postcode,
// suburb and Set-dealer are all handled by the shared `handleLocationModal`
// helper, so we trigger it from the postcode step. The two follow-up steps
// then become no-ops because the modal is already dismissed.

function _isNa(v) {
  if (!v) return true;
  const s = String(v).trim().toLowerCase();
  return s === '' || s === 'na' || s === 'n/a' || s === '-';
}

When('I enter postcode from test data', async function () {
  const postcode = _resolveRoapField(this, '', 'postcode', 'Postcode', 'POSTCODE') || '2000';
  console.log(`📍 Handling location modal with postcode: ${postcode}`);
  await handleLocationModal(this.page, postcode);
  this._locationDismissed = true;
});

When('I select the suburb from test data', async function () {
  // handleLocationModal (called by the postcode step) already picks the first
  // suburb result. Nothing to do here.
  if (this._locationDismissed) {
    console.log('ℹ️  Suburb already selected by location modal — no-op');
    return;
  }
  console.log('ℹ️  Location modal was not dismissed by postcode step; nothing to do');
});

When('I click on {string} button', async function (buttonName) {
  // Set dealer was clicked inside handleLocationModal, so skip duplicate clicks.
  if (/^\s*set\s+dealer\s*$/i.test(buttonName) && this._locationDismissed) {
    console.log('ℹ️  "Set dealer" already clicked by location modal — no-op');
    return;
  }
  await this.clickButton(buttonName);
  await this.page.waitForTimeout(1000);
});

When('I select Site_Variant {string} from test data', async function (variantArg) {
  const variant = _resolveRoapField(this, variantArg,
    'Site_Variant', 'Site Variant', 'SiteVariant', 'site_variant');
  assert.ok(variant, 'No Site_Variant — check "Driveaway Price - Test Data".');
  await selectConsumerVariant(this.page, variant);
});

When('I select Site_Powertrain {string} from test data', async function (powerArg) {
  const powertrain = _resolveRoapField(this, powerArg,
    'Site_Powertrain', 'Site Powertrain', 'SitePowertrain', 'site_powertrain', 'Powertrain');
  if (_isNa(powertrain)) {
    console.log('ℹ️  No Site_Powertrain to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, powertrain);
});

When('I select Extended Range Option Pack from test data', async function () {
  const option = _resolveRoapField(this, '',
    'Extended Range Option Pack', 'ExtendedRangeOptionPack', 'extended_range_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Extended Range Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Roof Basket Option Pack from test data', async function () {
  const option = _resolveRoapField(this, '',
    'Roof Basket Option Pack', 'RoofBasketOptionPack', 'roof_basket_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Roof Basket Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Site_Transmission {string} from test data', async function (transArg) {
  const transmission = _resolveRoapField(this, transArg,
    'Site_Transmission', 'Site Transmission', 'SiteTransmission', 'site_transmission', 'Transmission');
  if (_isNa(transmission)) {
    console.log('ℹ️  No Site_Transmission to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, transmission);
});

Then('I verify the captured driveaway price matches on calculator page', async function () {
  const roapPrice = this.roapDriveawayPrice;
  assert.ok(Number.isFinite(roapPrice),
    'ROAP Driveaway price was not captured — the capture step must run first.');

  // The authoritative consumer value comes from the variantpricecalc XHR
  // response (finalDriveAwayPrice). Give any in-flight request a brief
  // window to land, then fall back to scraping the popup if necessary.
  if (!Number.isFinite(this.cpcDriveawayFromNetwork)) {
    await this.page
      .waitForResponse(r => /variantpricecalc/i.test(r.url()) && r.ok(), { timeout: 8000 })
      .catch(() => null);
  }
  await this.page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
  await this.page.waitForTimeout(800);

  let cpcPrice = null;
  let source = '';
  if (Number.isFinite(this.cpcDriveawayFromNetwork)) {
    cpcPrice = this.cpcDriveawayFromNetwork;
    source = 'network (variantpricecalc.finalDriveAwayPrice)';
  } else {
    const captured = await this.page.evaluate(() => {
      function visible(el) {
        const r = el.getBoundingClientRect();
        if (r.width === 0 || r.height === 0) return false;
        const cs = window.getComputedStyle(el);
        return cs.visibility !== 'hidden' && cs.display !== 'none';
      }
      const labelRe = /drive\s*-?\s*away|driveaway/i;
      const all = Array.from(document.querySelectorAll('body *')).filter(visible);
      const hits = [];
      for (const el of all) {
        const t = (el.textContent || '').replace(/\s+/g, ' ').trim();
        if (!t || t.length > 200) continue;
        if (!labelRe.test(t)) continue;
        const m = t.match(/\$\s*([\d,]+(?:\.\d{1,2})?)/);
        if (!m) continue;
        const r = el.getBoundingClientRect();
        hits.push({ text: t, price: m[1], area: r.width * r.height });
      }
      if (hits.length === 0) return { error: 'No "Driveaway $..." text found on calculator price summary.' };
      hits.sort((a, b) => a.area - b.area);
      return { text: hits[0].price, context: hits[0].text };
    });
    if (captured.error) throw new Error(captured.error);
    cpcPrice = Number.parseFloat(String(captured.text).replace(/[^0-9.]/g, ''));
    assert.ok(Number.isFinite(cpcPrice), `Calculator driveaway "${captured.text}" is not a number.`);
    source = `popup DOM ("${captured.context}")`;
  }

  this.cpcDriveawayPrice = cpcPrice;
  console.log(`📌 Calculator Driveaway price: $${cpcPrice.toLocaleString()} [source: ${source}]`);
  console.log(`📊 Comparison — ROAP: $${roapPrice.toLocaleString()}  |  Calculator: $${cpcPrice.toLocaleString()}`);

  // Compare whole-dollar amounts only (ignore cent rounding differences).
  assert.strictEqual(
    Math.trunc(cpcPrice),
    Math.trunc(roapPrice),
    `Driveaway price mismatch — ROAP $${roapPrice} vs Calculator $${cpcPrice}`
  );
  console.log('✅ Driveaway prices match (whole-dollar).');
});

// ── Auto-appended steps ──────────────────────────────────────────

Given('I navigate to the ROAP login page {string}', async function (url) {
  // The feature has no Examples table, so `url` arrives as the literal
  // placeholder "<roap_url>". Resolve the real URL from the test-data sheet.
  const target = _resolveRoapField(this, url, 'roap_url', 'ROAP URL', 'ROAP_URL', 'url', 'URL');
  assert.ok(/^https?:\/\//i.test(target),
    `ROAP URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a roap_url value.`);
  _setupNetworkIntercept(this);
  console.log(`📋 Navigating to ROAP login: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter username {string} and password {string}', async function (userArg, passArg) {
  const username = _resolveRoapField(this, userArg, 'username', 'Username', 'user name', 'email', 'Email');
  const password = _resolveRoapField(this, passArg, 'password', 'Password', 'pass');
  await _fillRoapCredentials(this.page, username, password);
});

When('I select the Vehicle {string} from the table', async function (vehicleArg) {
  const vehicle = _resolveRoapField(this, vehicleArg, 'Vehicle', 'vehicle', 'Model', 'model');
  assert.ok(vehicle, 'No Vehicle value — check "Driveaway Price - Test Data" has a Vehicle column.');
  console.log(`🖱️  Selecting Vehicle via Model filter: ${vehicle}`);
  await _selectFromRoapColumnFilter(this.page, { value: vehicle });
  console.log(`✅ Model filter applied: ${vehicle}`);
});

// Variant / Engine / Transmission are column values on the table rows (not
// filter popovers). Stash the criteria; the capture step matches the row.
When('I select the ROAP Variant {string} from the table', async function (variantArg) {
  this.roapVariant = _resolveRoapField(this, variantArg,
    'ROAP Variant', 'ROAP_Variant', 'roap_variant', 'Variant', 'variant', 'Variant Group');
  assert.ok(this.roapVariant, 'No Variant value — check "Driveaway Price - Test Data" has a ROAP Variant column.');
  console.log(`📋 ROAP Variant criterion stored: ${this.roapVariant}`);
});

When('I select the ROAP Engine {string} from the table', async function (engineArg) {
  this.roapEngine = _resolveRoapField(this, engineArg,
    'ROAP Engine', 'ROAP_Engine', 'roap_engine', 'Engine', 'engine');
  assert.ok(this.roapEngine, 'No Engine value — check "Driveaway Price - Test Data" has a ROAP Engine column.');
  console.log(`📋 ROAP Engine criterion stored: ${this.roapEngine}`);
});

When('I select the ROAP Transmission {string} from the table', async function (transArg) {
  this.roapTransmission = _resolveRoapField(this, transArg,
    'ROAP Transmission', 'ROAP_Transmission', 'roap_transmission', 'Transmission', 'transmission');
  assert.ok(this.roapTransmission, 'No Transmission value — check "Driveaway Price - Test Data" has a ROAP Transmission column.');
  console.log(`📋 ROAP Transmission criterion stored: ${this.roapTransmission}`);
});

When('I navigate to the calculator page {string}', async function (url) {
  const target = _resolveRoapField(this, url,
    'CPC URL', 'CPCURL', 'cpc_url', 'cpcUrl', 'CpcUrl', 'URL', 'url');
  assert.ok(/^https?:\/\//i.test(target),
    `CPC URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a CPC URL value.`);
  _setupNetworkIntercept(this);
  _setupCpcPriceListener(this);
  console.log(`📋 Navigating to calculator: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter postcode {string} in the postcode field', async function (postcodeArg) {
  // The Hyundai calculator opens a "Set your location" modal on first visit.
  // handleLocationModal fills the postcode, picks the first suburb result and
  // clicks "Set dealer" — so the suburb/Set-dealer steps become no-ops.
  const postcode = _resolveRoapField(this, postcodeArg, 'postcode', 'Postcode', 'POSTCODE') || '2000';
  console.log(`📍 Handling location modal with postcode: ${postcode}`);
  await handleLocationModal(this.page, postcode);
  this._locationDismissed = true;
});

When('I select the suburb {string} from the dropdown', async function (suburbArg) {
  // The suburb was already picked inside handleLocationModal (postcode step).
  if (this._locationDismissed) {
    console.log('ℹ️  Suburb already selected by location modal — no-op');
    return;
  }
  console.log(`ℹ️  Location modal not dismissed; nothing to do for suburb "${suburbArg}"`);
});

When('I select Extended Range Option Pack {string} from test data', async function (optionArg) {
  const option = _resolveRoapField(this, optionArg,
    'Extended Range Option Pack', 'ExtendedRangeOptionPack', 'extended_range_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Extended Range Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Roof Basket Option Pack {string} from test data', async function (optionArg) {
  const option = _resolveRoapField(this, optionArg,
    'Roof Basket Option Pack', 'RoofBasketOptionPack', 'roof_basket_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Roof Basket Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

// ── Auto-appended steps ──────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// FCAI-based ROAP ↔ CPC price verification (new @DriveawayPrice flow).
//
// Field mapping (live-data verified, user-confirmed):
//   ROAP MLP        ==  CPC carpricecalculator `price`
//   ROAP Driveaway  ==  CPC carpricecalculator `priceEstimate`
// for the CPC variant whose `serviceId` equals the FCAI.
// ─────────────────────────────────────────────────────────────────────────────

const _toNum = (s) => {
  const n = Number.parseFloat(String(s == null ? '' : s).replace(/[^0-9.]/g, ''));
  return Number.isFinite(n) ? n : NaN;
};

// Recursively find the first object with serviceId === fcai in a parsed JSON blob.
function _findVariantByServiceId(obj, fcai, depth = 0) {
  if (!obj || depth > 8) return null;
  if (Array.isArray(obj)) {
    for (const it of obj) { const r = _findVariantByServiceId(it, fcai, depth + 1); if (r) return r; }
    return null;
  }
  if (typeof obj === 'object') {
    const sid = obj.serviceId ?? obj.serviceID ?? obj.variantId;
    if (sid != null && String(sid) === String(fcai)) return obj;
    for (const v of Object.values(obj)) { const r = _findVariantByServiceId(v, fcai, depth + 1); if (r) return r; }
  }
  return null;
}

// Scan the ROAP Offers table for the row whose FCAI column equals `fcai` and
// tag it with data-roap-target="1". Scrolls to load lazily-rendered rows.
async function _tagRoapFcaiRow(page, fcai) {
  const scan = () => page.evaluate((fcai) => {
    const norm = s => (s || '').replace(/\s+/g, ' ').trim();
    document.querySelectorAll('[data-roap-target]').forEach(e => e.removeAttribute('data-roap-target'));
    for (const t of Array.from(document.querySelectorAll('table'))) {
      const rows = Array.from(t.querySelectorAll('tr'));
      const header = rows.find(r => /\bFCAI\b/.test(r.innerText) && /\bMLP\b/.test(r.innerText));
      if (!header) continue;
      const heads = Array.from(header.querySelectorAll('th,td')).map(c => norm(c.innerText));
      const fcaiIdx = heads.findIndex(h => /^fcai$/i.test(h));
      const mlpIdx = heads.findIndex(h => /^mlp$/i.test(h));
      if (fcaiIdx === -1) continue;
      for (const r of rows) {
        if (r === header) continue;
        const cells = r.querySelectorAll('td,th');
        if (!cells.length || fcaiIdx >= cells.length) continue;
        if (norm(cells[fcaiIdx].textContent) === String(fcai)) {
          r.setAttribute('data-roap-target', '1');
          return { ok: true, model: norm(cells[1] && cells[1].textContent),
                   variantGroup: norm(cells[4] && cells[4].textContent),
                   mlp: norm(cells[mlpIdx] && cells[mlpIdx].textContent), mlpIdx };
        }
      }
    }
    return { ok: false };
  }, fcai);
  let res = await scan();
  for (let i = 0; i < 15 && !res.ok; i++) {
    await page.mouse.wheel(0, 4000);
    await page.waitForTimeout(500);
    res = await scan();
  }
  return res;
}

Given('I load the Driveaway Price test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  assert.ok(Object.keys(row).length, 'No "Driveaway Price - Test Data" row found in Confluence.');
  console.log(`📋 Driveaway test data: FCAI=${row.FCAI}, postcode=${row.postcode}, CPC=${row['CPC URL']}`);
});

Given('I open the ROAP URL from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row.roap_url || row['ROAP URL'] || row.ROAP_URL || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `ROAP URL is not a valid http(s) URL: "${target}".`);
  _setupNetworkIntercept(this);
  console.log(`📋 Opening ROAP: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 20000 }).catch(() => {});
  await this.page.waitForTimeout(1500);
});

When('I login using the username and password from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const username = (row.username || row.Username || row.email || row.Email || '').toString().trim();
  const password = (row.password || row.Password || row.pass || '').toString().trim();
  await _fillRoapCredentials(this.page, username, password);
  const btn = this.page.getByRole('button', { name: /log ?in|sign ?in|submit/i }).first();
  if (await btn.count()) await btn.click().catch(() => {});
  else await this.page.locator('button[type="submit"], input[type="submit"]').first().click().catch(() => {});
  await this.page.waitForLoadState('networkidle', { timeout: 25000 }).catch(() => {});
  await this.page.waitForTimeout(3000);
  const ok = await this.page.getByText(/Offers/i).first().isVisible().catch(() => false);
  console.log(`📋 ROAP login ${ok ? 'succeeded — Offers page visible' : 'submitted (Offers not confirmed)'}`);
});

When('I retrieve the FCAI from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  this.fcai = (row.FCAI || row.fcai || '').toString().trim();
  assert.ok(this.fcai, 'No FCAI value in "Driveaway Price - Test Data".');
  console.log(`📋 FCAI = ${this.fcai}`);
});

When('I search the vehicle using FCAI', async function () {
  assert.ok(this.fcai, 'FCAI not set — the retrieve step must run first.');
  await this.page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  const found = await _tagRoapFcaiRow(this.page, this.fcai);
  assert.ok(found.ok, `Could not find a row with FCAI=${this.fcai} in the ROAP Offers table.`);
  this.roapModel = found.model;
  console.log(`🔎 Found ROAP row: ${found.model} / ${found.variantGroup} (FCAI ${this.fcai}, MLP ${found.mlp})`);
});

When('I capture the MLP from ROAP', async function () {
  const row = this.page.locator('[data-roap-target="1"]').first();
  assert.ok(await row.count(), 'FCAI row not tagged — the search step must run first.');
  const mlpText = await this.page.evaluate(() => {
    const r = document.querySelector('[data-roap-target="1"]');
    const cells = r ? r.querySelectorAll('td,th') : [];
    return cells[9] ? cells[9].textContent.replace(/\s+/g, ' ').trim() : '';
  });
  const mlp = _toNum(mlpText);
  assert.ok(Number.isFinite(mlp) && mlp > 0, `Could not read a numeric MLP (got "${mlpText}").`);
  this.roapMlp = mlp;
  this.roapMlpText = mlpText;
  console.log(`📌 ROAP MLP = ${mlpText} (${mlp})`);
});

When('I capture the Driveaway Price from ROAP', async function () {
  // Expand the FCAI row's package sub-row via its checkbox (id="selected--<FCAI>").
  const cb = this.page.locator(`#selected--${this.fcai}`).first();
  if (await cb.count()) {
    if (!(await cb.isChecked().catch(() => false))) await cb.click({ force: true }).catch(() => {});
  } else {
    await this.page.locator('[data-roap-target="1"]').first().click().catch(() => {});
  }
  await this.page.waitForTimeout(1500);
  // Scope the search to the sibling rows immediately after the tagged FCAI row
  // (the expanded Driveaway sub-row) so we don't read another vehicle's offer.
  const info = await this.page.evaluate(() => {
    const norm = s => (s || '').replace(/\s+/g, ' ').trim();
    const re = /drive\s*-?\s*away[^$]*\$\s*([\d,]+(?:\.\d{1,2})?)/i;
    const target = document.querySelector('[data-roap-target="1"]');
    if (!target) return { err: 'no tagged row' };
    const found = [];
    let el = target.nextElementSibling, steps = 0;
    while (el && steps < 6) {
      const t = norm(el.textContent);
      const m = t.match(re);
      if (m) found.push({ text: t.slice(0, 160), amount: m[1] });
      el = el.nextElementSibling; steps++;
    }
    return { found };
  }, this.fcai);
  assert.ok(!info.err && info.found && info.found.length,
    `No "Driveaway $..." sub-row found after expanding the FCAI ${this.fcai} row.`);
  console.log(`📋 Driveaway sub-row candidates: ${JSON.stringify(info.found)}`);
  const da = _toNum(info.found[0].amount);
  assert.ok(Number.isFinite(da) && da > 0, `Could not parse driveaway amount from "${info.found[0].text}".`);
  this.roapDriveaway = da;
  this.roapDriveawayText = `$${info.found[0].amount}`;
  console.log(`📌 ROAP Driveaway = $${info.found[0].amount} (${da})`);
  // Save ONE ROAP evidence screenshot showing the FCAI row + expanded driveaway.
  // Named with the FCAI so the report's auxiliary-screenshot scan (which dedupes
  // by the name key) only ever surfaces this single "FCAI<n>" image.
  // Scroll the FCAI row into view and capture the VIEWPORT (not fullPage) so the
  // shot actually shows the FCAI row — a full-page shot of the 291-row table
  // would only show the top of the list, not the FCAI vehicle.
  try {
    const dir = 'screenshots'; if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const file = path.join(dir, `roap-Driveaway-FCAI${this.fcai}-${ts}.png`);
    const targetRow = this.page.locator('[data-roap-target="1"]').first();
    await targetRow.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    // Nudge up a little so the row sits below the sticky header, with its
    // expanded driveaway sub-row visible underneath.
    await this.page.evaluate(() => window.scrollBy(0, -120)).catch(() => {});
    await this.page.waitForTimeout(400);
    const buf = await this.page.screenshot({ fullPage: false });
    fs.writeFileSync(file, buf);
    if (typeof this.attach === 'function') this.attach(buf, 'image/png');
    this.roapScreenshotPath = file;
  } catch { /* ignore */ }
});

When('I open the CPC URL from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row['CPC URL'] || row.CPCURL || row.cpc_url || row.cpcUrl || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `CPC URL is not a valid http(s) URL: "${target}".`);
  // Capture the carpricecalculator API (its variants carry serviceId → price/priceEstimate).
  this._cpcCarPriceCalc = null;
  if (!this._cpcCarPriceListener) {
    this.page.on('response', async (resp) => {
      try {
        if (!/carpricecalculator/i.test(resp.url()) || !resp.ok()) return;
        const body = await resp.text().catch(() => '');
        const json = body ? JSON.parse(body) : null;
        if (json) { this._cpcCarPriceCalc = json; this._cpcCarPriceCalcUrl = resp.url(); }
      } catch { /* ignore */ }
    });
    this._cpcCarPriceListener = true;
  }
  console.log(`📋 Opening CPC: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
});

When('I set the dealer using the postcode and suburb from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const postcode = (row.postcode || row.Postcode || '2000').toString().trim();
  console.log(`📍 Setting dealer via postcode ${postcode}`);
  await handleLocationModal(this.page, postcode);
  // Wait for the carpricecalculator API to return (fires once the dealer is set).
  for (let i = 0; i < 30 && !this._cpcCarPriceCalc; i++) await this.page.waitForTimeout(500);
  assert.ok(this._cpcCarPriceCalc,
    'CPC carpricecalculator API response was not captured after setting the dealer.');
  console.log(`📋 Captured CPC pricing API: ${this._cpcCarPriceCalcUrl}`);
});

When('I locate the vehicle whose serviceId equals the FCAI', async function () {
  assert.ok(this._cpcCarPriceCalc, 'CPC pricing API not captured — the set-dealer step must run first.');
  assert.ok(this.fcai, 'FCAI not set.');
  const rec = _findVariantByServiceId(this._cpcCarPriceCalc, this.fcai);
  assert.ok(rec, `No CPC variant with serviceId=${this.fcai} in the carpricecalculator response.`);
  this.cpcPrice = _toNum(rec.price);
  this.cpcPriceEstimate = _toNum(rec.priceEstimate);
  console.log(`📌 CPC serviceId ${this.fcai}: variantGroup="${rec.variantGroup}", price=${this.cpcPrice}, priceEstimate=${this.cpcPriceEstimate}`);

  // Surface the carpricecalculator response (the matched serviceId variant) in
  // the report's API Payload panel. The `source` includes "verification" so
  // world.js's findFormSubmissionCall picks THIS call over any tracking XHRs.
  if (Array.isArray(this._capturedApiPayloads)) {
    this._capturedApiPayloads.push({
      url: this._cpcCarPriceCalcUrl || 'carpricecalculator',
      method: 'GET',
      requestBody: '',
      requestHeaders: {},
      statusCode: 200,
      responseHeaders: { 'content-type': 'application/json' },
      responseBody: JSON.stringify(rec, null, 2),
      timestamp: new Date().toISOString(),
      source: 'roap-carpricecalculator-verification',
    });
    console.log(`📎 carpricecalculator payload (serviceId ${this.fcai}) captured for the report`);
  }
});

Then('I verify the CPC priceEstimate matches the ROAP MLP', async function () {
  // Confirmed mapping: ROAP MLP  ==  CPC `price`.
  assert.ok(Number.isFinite(this.roapMlp), 'ROAP MLP not captured.');
  assert.ok(Number.isFinite(this.cpcPrice), 'CPC price not captured.');
  const diff = Math.abs(this.roapMlp - this.cpcPrice);
  console.log(`🔍 MLP check — ROAP MLP=$${this.roapMlp} vs CPC price=$${this.cpcPrice} (diff ${diff.toFixed(2)})`);
  assert.ok(diff <= 1, `MLP mismatch: ROAP MLP $${this.roapMlp} != CPC price $${this.cpcPrice}`);
  console.log('✅ MLP matches');
});

Then('I verify the CPC Estimated Drive Away price matches the ROAP Driveaway Price', async function () {
  // Confirmed mapping: ROAP Driveaway  ==  CPC `priceEstimate`.
  assert.ok(Number.isFinite(this.roapDriveaway), 'ROAP Driveaway not captured.');
  assert.ok(Number.isFinite(this.cpcPriceEstimate), 'CPC priceEstimate not captured.');
  const diff = Math.abs(this.roapDriveaway - this.cpcPriceEstimate);
  console.log(`🔍 Driveaway check — ROAP Driveaway=$${this.roapDriveaway} vs CPC priceEstimate=$${this.cpcPriceEstimate} (diff ${diff.toFixed(2)})`);
  assert.ok(diff <= 1, `Driveaway mismatch: ROAP Driveaway $${this.roapDriveaway} != CPC priceEstimate $${this.cpcPriceEstimate}`);
  console.log('✅ Driveaway matches');
});
