// @protected
/**
 * Auto-Generated Step Definitions for: Hyundai Contact a dealer - Verify status code in API Payload
 * Source: CAD-smoke.feature
 * Generated: 2026-04-13T23:44:06.820Z
 * Target URL: https://stage.hyundai.com.au/au/en/contact-a-dealer
 *
 * DOM Field Map:
 *   "First Name*" → #cad-page-first-name
 *   "Last Name*" → #cad-page-last-name
 *   "Email Address*" → #cad-page-email-address
 *   "Phone Number*" → #cad-page-phone-number
 *   "When are you likely to purchase?" → #cad-page-purchase-time
 *   "Model*" → #cad-page-model
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user navigates to Contact a dealer page', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  const pageKey = 'contact a dealer';
  const url = (this.pageUrls && (this.pageUrls[pageKey]
    || Object.entries(this.pageUrls).find(([k]) => k.includes(pageKey) || pageKey.includes(k))?.[1]))
    || 'https://stage.hyundai.com.au/au/en/contact-a-dealer';
  console.log(`📋 Navigating to ${pageKey}: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

Given('the user has selected dealer', async function () {
  const data = this.contactDealerData?.[0] || {};
  const postcode = (data['Set Location'] || data['Postcode'] || data['postcode'] || '2000').toString();
  console.log(`📋 Setting dealer location with postcode: ${postcode}`);

  // Dismiss cookie consent if present
  const cookieBtn = this.page.locator('#onetrust-accept-btn-handler, button:has-text("Accept All"), button:has-text("Accept all")').first();
  if ((await cookieBtn.count()) > 0 && (await cookieBtn.isVisible().catch(() => false))) {
    await cookieBtn.click().catch(() => {});
    await this.page.waitForTimeout(1000);
  }

  // Click Set location button
  const setLocBtn = this.page.locator('div[role="button"]:has-text("Set location"), button:has-text("Set location"), a:has-text("Set location")').first();
  if (!((await setLocBtn.count()) > 0 && (await setLocBtn.isVisible().catch(() => false)))) {
    console.log('⚠️ Set location button not found — skipping');
    return;
  }
  await setLocBtn.scrollIntoViewIfNeeded().catch(() => {});
  await setLocBtn.click({ timeout: 5000 });
  await this.page.waitForTimeout(1500);

  // Find visible modal input (there can be two with same ID, only one visible)
  const modalInputs = this.page.locator('.hyu-postcode-modal input#locaion-modal-input');
  let modalInput = null;
  for (let i = (await modalInputs.count()) - 1; i >= 0; i--) {
    const el = modalInputs.nth(i);
    if (await el.isVisible().catch(() => false)) { modalInput = el; break; }
  }
  if (!modalInput) {
    console.log('⚠️ No visible modal input — closing modal');
    await this.page.keyboard.press('Escape');
    return;
  }

  await modalInput.fill(postcode);
  await this.page.waitForTimeout(500);
  await modalInput.press('Enter');
  await this.page.waitForTimeout(2000);

  // Click first result
  const resultItem = this.page.locator('.tingle-modal--visible .hyu-postcode-modal--location-list li').first();
  if ((await resultItem.count()) > 0 && (await resultItem.isVisible().catch(() => false))) {
    await resultItem.click();
    await this.page.waitForTimeout(3000);
    // Click Set dealer button
    const setDealerBtn = this.page.locator('.tingle-modal--visible .js-hyu-postcode-modal--btn-set-dealer, .tingle-modal--visible button:has-text("Set dealer")').first();
    if ((await setDealerBtn.count()) > 0 && (await setDealerBtn.isVisible().catch(() => false))) {
      await setDealerBtn.click();
      await this.page.waitForTimeout(2000);
    }
  } else {
    console.log('⚠️ No location results — closing modal');
    await this.page.keyboard.press('Escape');
    await this.page.waitForTimeout(500);
  }
  console.log(`📋 Dealer location set to postcode: ${postcode}`);
});

When('the user enters purchase intent', async function () {
  const data = this.contactDealerData?.[0] || {};
  const purchaseTime = data['Purchase Timeline'] || data['Purchase Time'] || data['When Purchase'] || '';
  // DOM-mapped: "When are you likely to purchase?" → #cad-page-purchase-time
  const dropdown = this.page.locator('#cad-page-purchase-time').first();
  if ((await dropdown.count()) > 0) {
    await dropdown.scrollIntoViewIfNeeded().catch(() => {});
    if (purchaseTime) {
      await dropdown.selectOption({ label: purchaseTime }).catch(async () => {
        const opts = await dropdown.locator('option').allTextContents();
        const match = opts.find(o => o.trim().toLowerCase().includes(purchaseTime.toLowerCase()));
        if (match) await dropdown.selectOption({ label: match.trim() }).catch(() => {});
      });
    }
    // Ensure a real option is selected (not a placeholder)
    const val = await dropdown.inputValue().catch(() => '');
    if (!val) {
      const options = await dropdown.locator('option').all();
      for (const opt of options) {
        const v = await opt.getAttribute('value');
        const t = (await opt.textContent() || '').trim();
        if (v && t && !/when|select|choose/i.test(t)) {
          await dropdown.selectOption({ value: v });
          break;
        }
      }
    }
    const finalVal = await dropdown.inputValue().catch(() => '');
    console.log(`📋 Selected purchase intent: "${finalVal}"`);
  } else {
    console.log('⚠️ Purchase time dropdown #cad-page-purchase-time not found');
  }
});

When('the user selects model and powertrain', async function () {
  const data = this.contactDealerData?.[0] || {};
  const model = data['Model'] || data['Model Of Interest'] || '';
  const powertrain = data['Powertrain'] || data['Fuel Type'] || data['Energy Type'] || data['FuelType'] || '';

  // ── Step 1: Select Model ──────────────────────────────────────────────────
  // DOM-mapped: "Model*" → #cad-page-model
  const modelDropdown = this.page.locator('#cad-page-model').first();
  if ((await modelDropdown.count()) > 0) {
    await modelDropdown.scrollIntoViewIfNeeded().catch(() => {});
    if (model) {
      await modelDropdown.selectOption({ label: model }).catch(async () => {
        const opts = await modelDropdown.locator('option').allTextContents();
        const match = opts.find(o => o.trim().toLowerCase().includes(model.toLowerCase()));
        if (match) await modelDropdown.selectOption({ label: match.trim() }).catch(() => {});
        else {
          const first = opts.find(o => { const v = o.trim(); return v && !/select|model/i.test(v); });
          if (first) await modelDropdown.selectOption({ label: first.trim() }).catch(() => {});
        }
      });
    } else {
      const opts = await modelDropdown.locator('option').allTextContents();
      const first = opts.find(o => { const v = o.trim(); return v && !/select|model/i.test(v); });
      if (first) await modelDropdown.selectOption({ label: first.trim() }).catch(() => {});
    }
    console.log(`📋 Selected model: "${await modelDropdown.inputValue().catch(() => '')}"`); 
  } else {
    console.log('⚠️ Model dropdown #cad-page-model not found');
  }

  // ── Step 2: Wait for Powertrain / Energy Type dropdown ───────────────────
  // After model selection the page dynamically injects a fuel/energy-type
  // dropdown (id="cad-page-energy-type"). Wait up to 5 seconds for it.
  const powertrainDropdown = this.page.locator('#cad-page-energy-type, select[name="FuelType__c"], select[id*="energy" i], select[id*="powertrain" i], select[id*="fuel" i]').first();
  const ptVisible = await powertrainDropdown.waitFor({ state: 'visible', timeout: 5000 }).then(() => true).catch(() => false);
  if (ptVisible) {
    await powertrainDropdown.scrollIntoViewIfNeeded().catch(() => {});
    if (powertrain) {
      await powertrainDropdown.selectOption({ label: powertrain }).catch(async () => {
        const opts = await powertrainDropdown.locator('option').allTextContents();
        const match = opts.find(o => o.trim().toLowerCase().includes(powertrain.toLowerCase()));
        if (match) await powertrainDropdown.selectOption({ label: match.trim() }).catch(() => {});
        else {
          const first = opts.find(o => { const v = o.trim(); return v && !/select|choose|--/i.test(v); });
          if (first) await powertrainDropdown.selectOption({ label: first.trim() }).catch(() => {});
        }
      });
    } else {
      // No test data — pick first real option
      const opts = await powertrainDropdown.locator('option').allTextContents();
      const first = opts.find(o => { const v = o.trim(); return v && !/select|choose|--/i.test(v); });
      if (first) await powertrainDropdown.selectOption({ label: first.trim() }).catch(() => {});
    }
    console.log(`📋 Selected powertrain: "${await powertrainDropdown.inputValue().catch(() => '')}"`); 
  } else {
    console.log('ℹ️  Powertrain dropdown did not appear — model may not require it');
  }
  await this.page.waitForTimeout(500);
});

When('the user accepts the marketing authorisation', async function () {
  // Marketing / newsletter consent checkbox
  const checkbox = this.page.locator(
    'input[type="checkbox"][name*="marketing" i], input[type="checkbox"][name*="newsletter" i], input[type="checkbox"][id*="marketing" i]'
  ).first();
  // Wait for it to be present before interacting
  await checkbox.waitFor({ state: 'attached', timeout: 8000 }).catch(() => {});
  if ((await checkbox.count()) > 0) {
    await checkbox.scrollIntoViewIfNeeded().catch(() => {});
    await this.page.waitForTimeout(400);
    const isChecked = await checkbox.isChecked().catch(() => false);
    if (!isChecked) {
      const parentLabel = checkbox.locator('xpath=ancestor::label[1]').first();
      if ((await parentLabel.count()) > 0) {
        await parentLabel.click({ force: true, timeout: 3000 }).catch(async () => {
          await checkbox.evaluate(el => el.click()).catch(() => {});
        });
      } else {
        await checkbox.evaluate(el => el.click()).catch(() => {});
      }
    }
    console.log('📋 Accepted marketing authorisation');
  } else {
    console.log('⚠️ Marketing authorisation checkbox not found — skipping');
  }
});

When('the user submits the contact a dealer form', async function () {
  // Use the specific CAD form submit button (scoped to the form to avoid nav/search buttons)
  const submitBtn = this.page
    .locator('form button[type="submit"], .hyu-page-form button[type="submit"], .cad-form button[type="submit"], button[type="submit"]')
    .filter({ hasNotText: /search|find|go|cancel/i })
    .last();
  // Scroll into view first, then wait for visibility
  if ((await submitBtn.count()) > 0) {
    await submitBtn.scrollIntoViewIfNeeded({ timeout: 5000 }).catch(() => {});
    await this.page.waitForTimeout(500);
    // Wait up to 5s for it to become visible after scroll
    await submitBtn.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
    if (await submitBtn.isVisible().catch(() => false)) {
      await submitBtn.evaluate(el => el.click()).catch(async () => {
        await submitBtn.click({ force: true }).catch(() => {});
      });
      console.log('📋 Clicked submit button');
    } else {
      // Force-click even if not fully visible (may be clipped by overflow)
      await submitBtn.click({ force: true }).catch(() => {});
      console.log('📋 Force-clicked submit button (not fully visible)');
    }
  } else {
    console.log('⚠️ No submit button found — using keyboard submit');
    await this.page.keyboard.press('Enter');
  }
  // Wait for the network to settle so the API response is captured before assertions run.
  // Try networkidle first (up to 15s), then fall back to a fixed 8s wait.
  await this.page.waitForLoadState('networkidle', { timeout: 15000 }).catch(async () => {
    console.log('ℹ️  networkidle not reached — waiting 8s for API response');
    await this.page.waitForTimeout(8000);
  });
  // Give the CDP hook an extra moment to flush the last captured payload
  await this.page.waitForTimeout(1500);
  // The CAD form shows "We are processing your request..." while the API is still in-flight.
  // Wait up to 20s for that text to disappear before moving on.
  const _processingStart = Date.now();
  while (Date.now() - _processingStart < 20000) {
    const _processing = await this.page.evaluate(() =>
      (document.body.innerText || '').toLowerCase().includes('processing your request')
    ).catch(() => false);
    if (!_processing) break;
    await this.page.waitForTimeout(1000);
  }
  // Extra settle time after processing spinner disappears
  await this.page.waitForTimeout(1000);
  console.log(`📋 Submit settled. Captured API payloads: ${this._capturedApiPayloads?.length || 0}`);
});

Then('the form should be submitted successfully', async function () {
  // Multi-signal success check (mirrors contact_us / talk-to-an-expert):
  //   1) visible thank-you / success / confirm element
  //   2) success-bearing URL (thank-you, success, confirm, complete)
  //   3) confirmation copy on the page
  //   4) a 2xx form-submission API response captured by the network listener
  // Wait up to 15s for any signal to appear — the CAD form sometimes redraws slowly
  // after the API resolves.
  const _start = Date.now();
  let visible = false, urlOk = false, textOk = false, apiOk = false;
  while (Date.now() - _start < 15000) {
    const _success = this.page.locator(
      '[class*="thank" i], [class*="success" i], [class*="confirm" i], [class*="all-done" i], [class*="complete" i]'
    ).first();
    visible = (await _success.count()) > 0 && (await _success.isVisible().catch(() => false));
    const _url = this.page.url();
    urlOk = /thank|success|confirm|complete/i.test(_url);
    textOk = await this.page.getByText(
      /thank you|thank-you|we.?ll be in touch|received your enquiry|enquiry submitted|submitted successfully|we have received|your enquiry has been sent/i
    ).first().isVisible().catch(() => false);
    // Form-submission endpoints (filter out tracking pixels)
    const _trackingDomains = /google|analytics|doubleclick|snapchat|linkedin|twitter|insight|marketo|mktoresp|facebook|gtag|pixel|hotjar|clarity|webevents/i;
    const _formPathPattern = /content\/api|\/api\/|\/form\/|\/submit|\/enquir|\/lead|\/contact-?a-?dealer|\/customer/i;
    apiOk = Array.isArray(this._capturedApiPayloads) && this._capturedApiPayloads.some(p =>
      (p.method === 'POST' || p.method === 'PUT') &&
      p.status >= 200 && p.status < 300 &&
      !_trackingDomains.test(p.url || '') &&
      _formPathPattern.test(p.url || '')
    );
    if (visible || urlOk || textOk || apiOk) break;
    await this.page.waitForTimeout(500);
  }
  console.log(`📋 CAD success check — visibleEl=${visible} urlOk=${urlOk} textOk=${textOk} apiOk=${apiOk}`);
  this.successMessage = { displayed: visible || textOk };
  assert.ok(visible || urlOk || textOk || apiOk, 'the form should be submitted successfully');
});

When('the user leave the last name blank', async function () {
  // DOM-mapped: "Last Name*" → #cad-page-last-name
  const lastNameField = this.page.locator('#cad-page-last-name').first();
  if ((await lastNameField.count()) > 0) {
    await lastNameField.clear().catch(() => {});
    await lastNameField.fill('');
    console.log('📋 Left last name field empty');
  } else {
    console.log('⚠️ Last name field #cad-page-last-name not found');
  }
});

Then('a last name validation error should be displayed', async function () {
  await this.page.waitForTimeout(2000);
  // The CAD form uses Bootstrap-style .invalid-feedback divs for validation errors.
  // Try in order: specific last-name error → any invalid-feedback → any role=alert → submit still visible
  const errorSelectors = [
    // Most specific: invalid-feedback inside the last-name form group
    '#cad-page-last-name ~ .invalid-feedback',
    '#cad-page-last-name ~ div.invalid-feedback',
    // Parent form-group contains an invalid-feedback child
    '#cad-page-last-name',  // used below with closest() walk
    // Generic invalid-feedback with matching text
    '.invalid-feedback:has-text("last name")',
    '.invalid-feedback:has-text("Last")',
    // Any visible invalid-feedback as broad fallback
    '.invalid-feedback',
    // ARIA alerts
    '[role="alert"]',
  ];

  let found = false;
  for (const sel of errorSelectors) {
    if (sel === '#cad-page-last-name') {
      // Walk up to form-group and look for .invalid-feedback child
      const result = await this.page.evaluate(() => {
        const input = document.querySelector('#cad-page-last-name');
        if (!input) return null;
        let parent = input.parentElement;
        for (let i = 0; i < 5; i++) {
          if (!parent) break;
          const fb = parent.querySelector('.invalid-feedback');
          if (fb && fb.offsetParent !== null) return (fb.textContent || '').trim();
          parent = parent.parentElement;
        }
        return null;
      });
      if (result) {
        console.log(`📋 Last name validation error (parent walk): "${result}"`);
        found = true;
        break;
      }
      continue;
    }
    try {
      const el = this.page.locator(sel).first();
      if ((await el.count()) > 0 && (await el.isVisible().catch(() => false))) {
        const text = (await el.textContent().catch(() => '')).trim();
        console.log(`📋 Last name validation error visible [${sel}]: "${text}"`);
        found = true;
        break;
      }
    } catch { /* try next */ }
  }

  // Final fallback: submit button still present means validation blocked submission
  if (!found) {
    const submitBtn = this.page.locator('button[type="submit"]').last();
    const submitVisible = (await submitBtn.count()) > 0 && (await submitBtn.isVisible().catch(() => false));
    if (submitVisible) {
      console.log('📋 Last name validation: submit button still visible → form submission was blocked');
      found = true;
    }
  }

  assert.ok(found, 'A last name validation error should be displayed (or submission should be blocked)');
});

When('the user submits the contact a dealer form without completing required fields', async function () {
  // Submit without filling any fields — all fields left blank
  const submitBtn = this.page.locator('button[type="submit"], button:has-text("Submit")').first();
  if ((await submitBtn.count()) > 0 && (await submitBtn.isVisible().catch(() => false))) {
    await submitBtn.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await submitBtn.evaluate(el => el.click()).catch(async () => {
      await submitBtn.click({ force: true }).catch(() => {});
    });
    console.log('📋 Submitted form without filling required fields');
  }
  await this.page.waitForTimeout(3000);
});

Then('the form should not be submitted', async function () {
  await this.page.waitForTimeout(2000);
  // Verify no success / thank-you message is shown
  const successEl = this.page.locator('.thank-you, [class*="thank-you"], [class*="success"], [class*="confirmation"]').first();
  const successVisible = (await successEl.count()) > 0 && (await successEl.isVisible().catch(() => false));
  const url = this.page.url();
  const redirected = /thank|confirm|success/i.test(url);
  assert.ok(!successVisible && !redirected, 'The form should NOT be submitted (no success message or redirect)');
});

When('the user enters a invalid email address', async function () {
  // Try CAD-specific selector first, then fall back to generic email field
  const emailField = this.page.locator(
    '#cad-page-email-address, #email, input[name="email"], input[type="email"]'
  ).first();
  if ((await emailField.count()) > 0 && (await emailField.isVisible().catch(() => false))) {
    await emailField.scrollIntoViewIfNeeded().catch(() => {});
    await emailField.clear().catch(() => {});
    await emailField.fill('invalid-email-address');
    console.log('📋 Entered invalid email address');
  } else {
    console.log('⚠️ Email field not found on this page');
  }
});

When('the user leaves phone number blank', async function () {
  // DOM-mapped: "Phone Number*" → #cad-page-phone-number
  const phoneField = this.page.locator('#cad-page-phone-number').first();
  if ((await phoneField.count()) > 0) {
    await phoneField.clear().catch(() => {});
    await phoneField.fill('');
    console.log('📋 Left phone number field empty');
  } else {
    console.log('⚠️ Phone field #cad-page-phone-number not found');
  }
});
