// @protected
/**
 * Auto-Generated Step Definitions for: Form submission on Customer Care
 * Source: contact_us.feature
 * Generated: 2026-04-28T05:37:17.116Z
 * Target URL: https://stage.hyundai.com.au/au/en/customer-care/contact-us
 *
 * DOM Field Map:
 *   "Title*" → #contact-us-page-title
 *   "First Name*" → #contact-us-page-first-name
 *   "Last Name*" → #contact-us-page-last-name
 *   "Email Address*" → #contact-us-page-email-address
 *   "Phone Number" → #contact-us-page-phone-number
 *   "Postcode*" → #contact-us-page-postcode
 *   "Yes/No*" → #contact-us-own-hyundai
 *   "Model of interest" → #contact-us-page-model
 *   "What are you enquiring about?*" → #contact-us-page-enquiry
 *   "Please outline your enquiry*" → #contact-us-page-enquiry-reason
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('I am a user on the the Customer Care page', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: customer care
  const _pageKeys = ["customer care"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan against keys
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
    if (!url) {
      // Slug scan against URL paths — handles "customer care" → ".../customer-care/..."
      const _slugEntry = Object.entries(this.pageUrls).find(([, u]) => {
        try {
          const _p = new URL(u).pathname.toLowerCase();
          return _pageKeys.some(pk => pk && (_p.includes(pk.replace(/\s+/g, '-')) || _p.includes(pk.replace(/\s+/g, ''))));
        } catch { return false; }
      });
      if (_slugEntry) url = _slugEntry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en/customer-care/contact-us';
  console.log(`📋 Navigating to customer care: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

Given('the user navigates to Contact Us', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: contact us
  const _pageKeys = ["contact us"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan against keys
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
    if (!url) {
      // Slug scan against URL paths — handles "customer care" → ".../customer-care/..."
      const _slugEntry = Object.entries(this.pageUrls).find(([, u]) => {
        try {
          const _p = new URL(u).pathname.toLowerCase();
          return _pageKeys.some(pk => pk && (_p.includes(pk.replace(/\s+/g, '-')) || _p.includes(pk.replace(/\s+/g, ''))));
        } catch { return false; }
      });
      if (_slugEntry) url = _slugEntry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en/customer-care/contact-us';
  console.log(`📋 Navigating to contact us: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

When('user fills Own Hyundai from test data', async function () {
  // Field: 'Own Hyundai' → DOM: Yes/No* [#contact-us-own-hyundai]
  // Data column candidates: Own Hyundai | Yes/No | Own | Owner
  const _dataKeys = ["Own Hyundai","Yes/No","Own","Owner"];
  const _norm = s => String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const _dataSets = [
    this.contactUsData, this.testDriveData, this.contactDealerData, this.bookAServiceData,
    ...(this.allConfluenceData ? Object.values(this.allConfluenceData) : []),
  ].filter(Boolean);
  let _val = '';
  outer: for (const _ds of _dataSets) {
    const _rows = Array.isArray(_ds) ? _ds : [_ds];
    for (const _row of _rows) {
      if (!_row || typeof _row !== 'object') continue;
      for (const _k of _dataKeys) {
        const _kn = _norm(_k);
        for (const _rk of Object.keys(_row)) {
          if (_norm(_rk) === _kn && _row[_rk] != null && String(_row[_rk]).trim() !== '') {
            _val = String(_row[_rk]); break outer;
          }
        }
      }
    }
  }
  console.log(`📝 'Own Hyundai' resolved value: "${_val}"`);
  const _el = this.page.locator('#contact-us-own-hyundai').first();
  if ((await _el.count()) > 0) {
    await _el.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    const _tag = (await _el.evaluate(e => e.tagName).catch(() => '')).toLowerCase();
    const _type = (await _el.getAttribute('type').catch(() => '')) || '';
    if (_tag === 'select') {
      if (_val) {
        // Wait for options to populate (cascading dropdowns load async after a parent select changes)
        await this.page.waitForFunction((el) => el && el.options && el.options.length > 1, await _el.elementHandle().catch(() => null), { timeout: 8000 }).catch(() => {});
        await _el.selectOption({ label: _val }).catch(async () => {
          const _opts = await _el.locator('option').allTextContents();
          const _m = _opts.find(o => o.trim().toLowerCase() === _val.toLowerCase())
                || _opts.find(o => o.trim().toLowerCase().includes(_val.toLowerCase()));
          if (_m) await _el.selectOption({ label: _m }).catch(async () => {
            await _el.evaluate((el, v) => {
              const opt = Array.from(el.options).find(o => o.text.trim() === v);
              if (opt) { el.value = opt.value; el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }
            }, _m);
          });
          // If still nothing selected, try matching by option VALUE (handles "Yes"/"No" labels with "true"/"false" values)
          const _curVal = await _el.inputValue().catch(() => '');
          if (!_curVal || /^select|^choose|^--/i.test(_curVal)) {
            await _el.selectOption({ value: _val }).catch(() => {});
            const _yesNo = /^(yes|y|true|1)$/i.test(_val) ? 'true' : (/^(no|n|false|0)$/i.test(_val) ? 'false' : null);
            if (_yesNo) await _el.selectOption({ value: _yesNo }).catch(() => {});
          }
        });
        // Trigger change so dependent selects (e.g. Model after Own Hyundai) cascade-load
        await _el.evaluate(el => { el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }).catch(() => {});
        await this.page.waitForTimeout(400);
        const _finalVal = await _el.inputValue().catch(() => '');
        const _finalText = await _el.evaluate(el => { const o = el.options[el.selectedIndex]; return o ? o.text.trim() : ''; }).catch(() => '');
        const _optsList = await _el.locator('option').allTextContents();
        // If the dropdown is empty (e.g. dependent on a parent select that wasn't enabled),
        // skip silently — this can be intentional per the test data (e.g. Own Hyundai="No" hides Model).
        if (_optsList.length <= 1) {
          console.log(`⏭  Skipped 'Own Hyundai' — dropdown has no options (likely disabled by a parent field). Resolved value was "${_val}".`);
        } else {
          console.log(`📝 Selected 'Own Hyundai' (DOM-mapped): value="${_finalVal}" text="${_finalText}"`);
        }
      }
    } else if (_type === 'checkbox' || _type === 'radio') {
      const _truthy = /^(yes|true|1|on|y)$/i.test(_val);
      const _checked = await _el.isChecked().catch(() => false);
      if (_truthy !== _checked) await _el.click({ force: true }).catch(() => {});
    } else {
      await _el.clear().catch(() => {});
      await _el.fill(_val);
      console.log(`📝 Filled 'Own Hyundai' (DOM-mapped): "${_val}"`);
    }
  } else if (_val) {
    await this.fillField('Own Hyundai', _val).catch(async () => {
      await this.selectDropdown('Own Hyundai', _val).catch(() => {});
    });
  }
  await this.page.waitForTimeout(500);
});

When('user fills Model of interest from test data', async function () {
  // Field: 'Model of interest' → DOM: Model of interest [#contact-us-page-model]
  // Data column candidates: Model of interest | Model | of interest
  const _dataKeys = ["Model of interest","Model","of interest"];
  const _norm = s => String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const _dataSets = [
    this.contactUsData, this.testDriveData, this.contactDealerData, this.bookAServiceData,
    ...(this.allConfluenceData ? Object.values(this.allConfluenceData) : []),
  ].filter(Boolean);
  let _val = '';
  outer: for (const _ds of _dataSets) {
    const _rows = Array.isArray(_ds) ? _ds : [_ds];
    for (const _row of _rows) {
      if (!_row || typeof _row !== 'object') continue;
      for (const _k of _dataKeys) {
        const _kn = _norm(_k);
        for (const _rk of Object.keys(_row)) {
          if (_norm(_rk) === _kn && _row[_rk] != null && String(_row[_rk]).trim() !== '') {
            _val = String(_row[_rk]); break outer;
          }
        }
      }
    }
  }
  console.log(`📝 'Model of interest' resolved value: "${_val}"`);
  const _el = this.page.locator('#contact-us-page-model').first();
  if ((await _el.count()) > 0) {
    await _el.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    const _tag = (await _el.evaluate(e => e.tagName).catch(() => '')).toLowerCase();
    const _type = (await _el.getAttribute('type').catch(() => '')) || '';
    if (_tag === 'select') {
      if (_val) {
        // Wait for options to populate (cascading dropdowns load async after a parent select changes)
        await this.page.waitForFunction((el) => el && el.options && el.options.length > 1, await _el.elementHandle().catch(() => null), { timeout: 8000 }).catch(() => {});
        await _el.selectOption({ label: _val }).catch(async () => {
          const _opts = await _el.locator('option').allTextContents();
          const _m = _opts.find(o => o.trim().toLowerCase() === _val.toLowerCase())
                || _opts.find(o => o.trim().toLowerCase().includes(_val.toLowerCase()));
          if (_m) await _el.selectOption({ label: _m }).catch(async () => {
            await _el.evaluate((el, v) => {
              const opt = Array.from(el.options).find(o => o.text.trim() === v);
              if (opt) { el.value = opt.value; el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }
            }, _m);
          });
          // If still nothing selected, try matching by option VALUE (handles "Yes"/"No" labels with "true"/"false" values)
          const _curVal = await _el.inputValue().catch(() => '');
          if (!_curVal || /^select|^choose|^--/i.test(_curVal)) {
            await _el.selectOption({ value: _val }).catch(() => {});
            const _yesNo = /^(yes|y|true|1)$/i.test(_val) ? 'true' : (/^(no|n|false|0)$/i.test(_val) ? 'false' : null);
            if (_yesNo) await _el.selectOption({ value: _yesNo }).catch(() => {});
          }
        });
        // Trigger change so dependent selects (e.g. Model after Own Hyundai) cascade-load
        await _el.evaluate(el => { el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }).catch(() => {});
        await this.page.waitForTimeout(400);
        const _finalVal = await _el.inputValue().catch(() => '');
        const _finalText = await _el.evaluate(el => { const o = el.options[el.selectedIndex]; return o ? o.text.trim() : ''; }).catch(() => '');
        const _optsList = await _el.locator('option').allTextContents();
        // If the dropdown is empty (e.g. dependent on a parent select that wasn't enabled),
        // skip silently — this can be intentional per the test data (e.g. Own Hyundai="No" hides Model).
        if (_optsList.length <= 1) {
          console.log(`⏭  Skipped 'Model of interest' — dropdown has no options (likely disabled by a parent field). Resolved value was "${_val}".`);
        } else {
          console.log(`📝 Selected 'Model of interest' (DOM-mapped): value="${_finalVal}" text="${_finalText}"`);
        }
      }
    } else if (_type === 'checkbox' || _type === 'radio') {
      const _truthy = /^(yes|true|1|on|y)$/i.test(_val);
      const _checked = await _el.isChecked().catch(() => false);
      if (_truthy !== _checked) await _el.click({ force: true }).catch(() => {});
    } else {
      await _el.clear().catch(() => {});
      await _el.fill(_val);
      console.log(`📝 Filled 'Model of interest' (DOM-mapped): "${_val}"`);
    }
  } else if (_val) {
    await this.fillField('Model of interest', _val).catch(async () => {
      await this.selectDropdown('Model of interest', _val).catch(() => {});
    });
  }
  await this.page.waitForTimeout(500);
});

When('user fills Enquiry About from test data', async function () {
  // Field: 'Enquiry About' → DOM: What are you enquiring about?* [#contact-us-page-enquiry]
  // Data column candidates: Enquiry About | What are you enquiring about | Enquiry | Reason | Subject
  const _dataKeys = ["Enquiry About","What are you enquiring about","Enquiry","Reason","Subject"];
  const _norm = s => String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const _dataSets = [
    this.contactUsData, this.testDriveData, this.contactDealerData, this.bookAServiceData,
    ...(this.allConfluenceData ? Object.values(this.allConfluenceData) : []),
  ].filter(Boolean);
  let _val = '';
  outer: for (const _ds of _dataSets) {
    const _rows = Array.isArray(_ds) ? _ds : [_ds];
    for (const _row of _rows) {
      if (!_row || typeof _row !== 'object') continue;
      for (const _k of _dataKeys) {
        const _kn = _norm(_k);
        for (const _rk of Object.keys(_row)) {
          if (_norm(_rk) === _kn && _row[_rk] != null && String(_row[_rk]).trim() !== '') {
            _val = String(_row[_rk]); break outer;
          }
        }
      }
    }
  }
  console.log(`📝 'Enquiry About' resolved value: "${_val}"`);
  const _el = this.page.locator('#contact-us-page-enquiry').first();
  if ((await _el.count()) > 0) {
    await _el.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    const _tag = (await _el.evaluate(e => e.tagName).catch(() => '')).toLowerCase();
    const _type = (await _el.getAttribute('type').catch(() => '')) || '';
    if (_tag === 'select') {
      if (_val) {
        // Wait for options to populate (cascading dropdowns load async after a parent select changes)
        await this.page.waitForFunction((el) => el && el.options && el.options.length > 1, await _el.elementHandle().catch(() => null), { timeout: 8000 }).catch(() => {});
        await _el.selectOption({ label: _val }).catch(async () => {
          const _opts = await _el.locator('option').allTextContents();
          const _m = _opts.find(o => o.trim().toLowerCase() === _val.toLowerCase())
                || _opts.find(o => o.trim().toLowerCase().includes(_val.toLowerCase()));
          if (_m) await _el.selectOption({ label: _m }).catch(async () => {
            await _el.evaluate((el, v) => {
              const opt = Array.from(el.options).find(o => o.text.trim() === v);
              if (opt) { el.value = opt.value; el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }
            }, _m);
          });
          // If still nothing selected, try matching by option VALUE (handles "Yes"/"No" labels with "true"/"false" values)
          const _curVal = await _el.inputValue().catch(() => '');
          if (!_curVal || /^select|^choose|^--/i.test(_curVal)) {
            await _el.selectOption({ value: _val }).catch(() => {});
            const _yesNo = /^(yes|y|true|1)$/i.test(_val) ? 'true' : (/^(no|n|false|0)$/i.test(_val) ? 'false' : null);
            if (_yesNo) await _el.selectOption({ value: _yesNo }).catch(() => {});
          }
        });
        // Trigger change so dependent selects (e.g. Model after Own Hyundai) cascade-load
        await _el.evaluate(el => { el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }).catch(() => {});
        await this.page.waitForTimeout(400);
        const _finalVal = await _el.inputValue().catch(() => '');
        const _finalText = await _el.evaluate(el => { const o = el.options[el.selectedIndex]; return o ? o.text.trim() : ''; }).catch(() => '');
        const _optsList = await _el.locator('option').allTextContents();
        // If the dropdown is empty (e.g. dependent on a parent select that wasn't enabled),
        // skip silently — this can be intentional per the test data (e.g. Own Hyundai="No" hides Model).
        if (_optsList.length <= 1) {
          console.log(`⏭  Skipped 'Enquiry About' — dropdown has no options (likely disabled by a parent field). Resolved value was "${_val}".`);
        } else {
          console.log(`📝 Selected 'Enquiry About' (DOM-mapped): value="${_finalVal}" text="${_finalText}"`);
        }
      }
    } else if (_type === 'checkbox' || _type === 'radio') {
      const _truthy = /^(yes|true|1|on|y)$/i.test(_val);
      const _checked = await _el.isChecked().catch(() => false);
      if (_truthy !== _checked) await _el.click({ force: true }).catch(() => {});
    } else {
      await _el.clear().catch(() => {});
      await _el.fill(_val);
      console.log(`📝 Filled 'Enquiry About' (DOM-mapped): "${_val}"`);
    }
  } else if (_val) {
    await this.fillField('Enquiry About', _val).catch(async () => {
      await this.selectDropdown('Enquiry About', _val).catch(() => {});
    });
  }
  await this.page.waitForTimeout(500);
});

When('user fills Outline Enquiry from test data', async function () {
  // Field: 'Outline Enquiry' → DOM: Please outline your enquiry* [#contact-us-page-enquiry-reason]
  // Data column candidates: Outline Enquiry | Please outline your enquiry | Outline | Enquiry | Comments | Message
  const _dataKeys = ["Outline Enquiry","Please outline your enquiry","Outline","Enquiry","Comments","Message"];
  const _norm = s => String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const _dataSets = [
    this.contactUsData, this.testDriveData, this.contactDealerData, this.bookAServiceData,
    ...(this.allConfluenceData ? Object.values(this.allConfluenceData) : []),
  ].filter(Boolean);
  let _val = '';
  outer: for (const _ds of _dataSets) {
    const _rows = Array.isArray(_ds) ? _ds : [_ds];
    for (const _row of _rows) {
      if (!_row || typeof _row !== 'object') continue;
      for (const _k of _dataKeys) {
        const _kn = _norm(_k);
        for (const _rk of Object.keys(_row)) {
          if (_norm(_rk) === _kn && _row[_rk] != null && String(_row[_rk]).trim() !== '') {
            _val = String(_row[_rk]); break outer;
          }
        }
      }
    }
  }
  console.log(`📝 'Outline Enquiry' resolved value: "${_val}"`);
  const _el = this.page.locator('#contact-us-page-enquiry-reason').first();
  if ((await _el.count()) > 0) {
    await _el.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    const _tag = (await _el.evaluate(e => e.tagName).catch(() => '')).toLowerCase();
    const _type = (await _el.getAttribute('type').catch(() => '')) || '';
    if (_tag === 'select') {
      if (_val) {
        // Wait for options to populate (cascading dropdowns load async after a parent select changes)
        await this.page.waitForFunction((el) => el && el.options && el.options.length > 1, await _el.elementHandle().catch(() => null), { timeout: 8000 }).catch(() => {});
        await _el.selectOption({ label: _val }).catch(async () => {
          const _opts = await _el.locator('option').allTextContents();
          const _m = _opts.find(o => o.trim().toLowerCase() === _val.toLowerCase())
                || _opts.find(o => o.trim().toLowerCase().includes(_val.toLowerCase()));
          if (_m) await _el.selectOption({ label: _m }).catch(async () => {
            await _el.evaluate((el, v) => {
              const opt = Array.from(el.options).find(o => o.text.trim() === v);
              if (opt) { el.value = opt.value; el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }
            }, _m);
          });
          // If still nothing selected, try matching by option VALUE (handles "Yes"/"No" labels with "true"/"false" values)
          const _curVal = await _el.inputValue().catch(() => '');
          if (!_curVal || /^select|^choose|^--/i.test(_curVal)) {
            await _el.selectOption({ value: _val }).catch(() => {});
            const _yesNo = /^(yes|y|true|1)$/i.test(_val) ? 'true' : (/^(no|n|false|0)$/i.test(_val) ? 'false' : null);
            if (_yesNo) await _el.selectOption({ value: _yesNo }).catch(() => {});
          }
        });
        // Trigger change so dependent selects (e.g. Model after Own Hyundai) cascade-load
        await _el.evaluate(el => { el.dispatchEvent(new Event('change', { bubbles: true })); el.dispatchEvent(new Event('input', { bubbles: true })); }).catch(() => {});
        await this.page.waitForTimeout(400);
        const _finalVal = await _el.inputValue().catch(() => '');
        const _finalText = await _el.evaluate(el => { const o = el.options[el.selectedIndex]; return o ? o.text.trim() : ''; }).catch(() => '');
        const _optsList = await _el.locator('option').allTextContents();
        // If the dropdown is empty (e.g. dependent on a parent select that wasn't enabled),
        // skip silently — this can be intentional per the test data (e.g. Own Hyundai="No" hides Model).
        if (_optsList.length <= 1) {
          console.log(`⏭  Skipped 'Outline Enquiry' — dropdown has no options (likely disabled by a parent field). Resolved value was "${_val}".`);
        } else {
          console.log(`📝 Selected 'Outline Enquiry' (DOM-mapped): value="${_finalVal}" text="${_finalText}"`);
        }
      }
    } else if (_type === 'checkbox' || _type === 'radio') {
      const _truthy = /^(yes|true|1|on|y)$/i.test(_val);
      const _checked = await _el.isChecked().catch(() => false);
      if (_truthy !== _checked) await _el.click({ force: true }).catch(() => {});
    } else {
      await _el.clear().catch(() => {});
      await _el.fill(_val);
      console.log(`📝 Filled 'Outline Enquiry' (DOM-mapped): "${_val}"`);
    }
  } else if (_val) {
    await this.fillField('Outline Enquiry', _val).catch(async () => {
      await this.selectDropdown('Outline Enquiry', _val).catch(() => {});
    });
  }
  await this.page.waitForTimeout(500);
});

When('the user clicks Send Enquiry', async function () {
  // DOM-mapped selector for 'Send Enquiry' button: button:has-text("Send Enquiry")
  const _domBtn = this.page.locator('button:has-text("Send Enquiry")');
  if ((await _domBtn.count()) > 0) {
    await _domBtn.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _domBtn.click({ force: true, timeout: 5000 });
    console.log("📋 Clicked 'Send Enquiry' [DOM-mapped]");
  } else {
    await this.clickButton('Send Enquiry');
  }
  await this.page.waitForTimeout(2000);
});

Then('the Contact us form submission is successful', async function () {
  await this.page.waitForTimeout(3000);
  // Multi-signal success check: visible thank-you/success element, success-bearing URL,
  // success text on page, OR a 2xx form-submission API response captured by network listener.
  const success = this.page.locator('[class*="thank"], [class*="success"], [class*="confirm"], [class*="all-done"], [class*="complete"]').first();
  const visible = (await success.count()) > 0 && (await success.isVisible().catch(() => false));
  const url = this.page.url();
  const urlOk = /thank|success|confirm|complete/i.test(url);
  const textOk = await this.page.getByText(/thank you|thank-you|we.?ll be in touch|received your enquiry|enquiry submitted|submitted successfully|we have received/i).first().isVisible().catch(() => false);
  const apiOk = Array.isArray(this.networkResponses) && this.networkResponses.some(r =>
    r && r.status >= 200 && r.status < 300 && /\/form\/|\blead|\benquir|\bcontact|\bsubmit/i.test(r.url || ''));
  console.log(`📋 Success check — visibleEl=${visible} urlOk=${urlOk} textOk=${textOk} apiOk=${apiOk}`);
  assert.ok(visible || urlOk || textOk || apiOk, 'the Contact us form submission is successful');
  this.successMessage = { displayed: true };
});

Then('a {string} confirmation message should be displayed', async function (param) {
  // Wait up to 15s for the confirmation to render — submission API + UI redraw can be slow.
  const _start = Date.now();
  let _hit = false;
  let _matchedBy = '';
  while (Date.now() - _start < 15000) {
    const _url = this.page.url();
    if (/thank|confirm|success/i.test(_url)) { _hit = true; _matchedBy = `url=${_url}`; break; }
    // Exact param text (case-insensitive, partial — handles "Your enquiry has been sent. Thank you.")
    const _exact = param.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const _exactRe = new RegExp(_exact, 'i');
    if (await this.page.getByText(_exactRe).first().isVisible().catch(() => false)) {
      _hit = true; _matchedBy = `exact text "${param}"`; break;
    }
    // Generic confirmation phrases
    if (await this.page.getByText(/thank you|thank-you|confirmation|enquiry has been sent|we.?ll be in touch/i).first().isVisible().catch(() => false)) {
      _hit = true; _matchedBy = 'generic text'; break;
    }
    const _el = this.page.locator('.thank-you, [class*="thank-you"], [class*="success" i], [class*="confirmation" i]').first();
    if ((await _el.count()) > 0 && (await _el.isVisible().catch(() => false))) {
      const _t = (await _el.innerText().catch(() => '')).trim();
      if (_t.length > 5) { _hit = true; _matchedBy = `css class (text=${_t.substring(0, 60)})`; break; }
    }
    await this.page.waitForTimeout(500);
  }
  // Fallback: enquiry-form API returned 2xx (filtered to actual submit endpoints, not analytics).
  if (!_hit) {
    const _apiOk = (this.networkResponses || []).some(r =>
      /enquir|talk-to|contact-us|contact-form|expert\/submit|leads?\b/i.test(r.url) &&
      !/rum|rcd|analytics|tealium|adobe|gtm|google/i.test(r.url) &&
      r.status >= 200 && r.status < 300);
    if (_apiOk) { _hit = true; _matchedBy = 'enquiry API 2xx'; }
  }
  console.log(`📋 Confirmation check: ${_hit ? '✅' : '❌'} (${_matchedBy || 'no match'})`);
  assert.ok(_hit, `Confirmation message "${param}" should be displayed`);
});
