// @protected
/**
 * Auto-Generated Step Definitions for: Hyundai Fleet Registration - Verify status code in API Payload
 * Source: FleetReg-smoke.feature
 * Generated: 2026-04-14T01:41:27.672Z
 * Target URL: https://stage.hyundai.com.au/au/en/fleet/registration
 *
 * DOM Field Map:
 *   "Title*" → #fleet-registration-page-title
 *   "First Name*" → #fleet-registration-page-first-name
 *   "Last Name*" → #fleet-registration-page-last-name
 *   "Phone Number*" → #fleet-registration-page-phone-number
 *   "Email Address*" → #fleet-registration-page-email-address
 *   "Position*" → #fleet-registration-page-position
 *   "ABN*" → #fleet-registration-page-abn
 *   "Company Name*" → #fleet-registration-page-company-name
 *   "Purchase Category*" → #fleet-registration-page-purchase-category
 *   "Industry*" → #fleet-registration-page-industry
 *   "Address*" → #fleet-registration-page-address
 *   "Suburb*" → #fleet-registration-page-suburb
 *   "State*" → #fleet-registration-page-state
 *   "Postcode*" → #fleet-registration-page-postcode
 *   "Fleet Size*" → #fleet-registration-page-fleet-size
 *   "Vehicle Replacement Policy - in months*" → #fleet-registration-page-replacement-months
 *   "Vehicle Replacement Policy - in kms*" → #fleet-registration-page-replacement-kms
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user navigates to Fleet Registration', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  const url = (this.pageUrls && (this.pageUrls['fleet registration'] || this.pageUrls['fleet']))
    || 'https://stage.hyundai.com.au/au/en/fleet/registration';

  // AEM staging requires a warm session/dispatcher cookie before serving some pages.
  // Visit the homepage first to establish cookies, then navigate to the target page.
  // Cache: only do the homepage+cookie warmup ONCE per process — subsequent scenarios reuse cookies.
  const baseUrl = (this.pageUrls && this.pageUrls['home'])
    || 'https://stage.hyundai.com.au/au/en';
  if (!global.__fleetSessionWarmed) {
    console.log(`📋 Warming up AEM session via homepage: ${baseUrl}`);
    await this.page.goto(baseUrl, { waitUntil: 'domcontentloaded', timeout: 60000 });
    const cookieBtn = this.page.locator('#onetrust-accept-btn-handler, button:has-text("Accept All"), button:has-text("Accept all")').first();
    if ((await cookieBtn.count()) > 0 && await cookieBtn.isVisible().catch(() => false)) {
      await cookieBtn.click().catch(() => {});
      console.log('📋 Accepted cookie consent on homepage');
    }
    global.__fleetSessionWarmed = true;
  }

  console.log(`📋 Navigating to Fleet Registration: ${url}`);
  await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });

  // Verify the page loaded correctly (not a 404)
  const pageTitle = await this.page.title().catch(() => '');
  const is404 = /404|not found/i.test(await this.page.locator('h1, h2').first().textContent().catch(() => ''));
  if (is404) {
    console.warn(`⚠️ Got 404 on first attempt — retrying navigation to: ${url}`);
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  }
  // Wait for the form to be present instead of arbitrary timeouts.
  await this.page.locator('form.fleet-registration, #fleet-registration-page-fleet-size').first().waitFor({ state: 'visible', timeout: 20000 }).catch(() => {});
  console.log(`📋 Fleet Registration page loaded — title: "${pageTitle}"`);
});

When('the user enters a Title', async function () {
  const data = this.fleetData?.[0] || {};
  const title = data['Title'] || data['Salutation'] || 'Mr';
  const select = this.page.locator('#fleet-registration-page-title, select[name*="title" i], select[name*="salutation" i]').first();
  if ((await select.count()) > 0) {
    await select.scrollIntoViewIfNeeded().catch(() => {});
    const options = await select.locator('option').allTextContents();
    const match = options.find(o => o.trim().toLowerCase() === title.toLowerCase())
      || options.find(o => o.trim().toLowerCase().includes(title.toLowerCase()));
    if (match) {
      await select.selectOption({ label: match.trim() }).catch(() => {});
    } else if (options.length > 1) {
      await select.selectOption({ index: 1 });
    }
    console.log(`📋 Selected Title: ${title}`);
  }
});

When('the user selects option on Person Submitting Form Same as Above', async function () {
  // The fleet form has a "Person submitting form same as above?" field with Yes/No radios:
  //   id="need2ndContact"    → Yes (person IS same as above)
  //   id="no-need2ndContact" → No
  // Read the Confluence test data value to decide which to pick.
  const data = this.fleetData?.[0] || {};
  const val = String(data['Person Submitting Form Same as Above'] || 'Yes').trim().toLowerCase();
  const radioId = (val === 'no') ? 'no-need2ndContact' : 'need2ndContact';
  const radio = this.page.locator(`#${radioId}`).first();
  if ((await radio.count()) > 0) {
    await radio.scrollIntoViewIfNeeded().catch(() => {});
    // Click the associated label (more reliable than clicking the hidden radio directly)
    const label = this.page.locator(`label[for="${radioId}"]`).first();
    if ((await label.count()) > 0) {
      await label.click({ force: true });
    } else {
      await radio.click({ force: true });
    }
    console.log(`📋 Selected Person Submitting Form Same as Above: ${val === 'no' ? 'No' : 'Yes'}`);
  } else {
    console.warn('⚠️  Person Submitting Form radio not found');
  }
  await this.page.waitForTimeout(300);
});

When('the user selects Position in the pulldown', async function () {
  const data = this.fleetData?.[0] || {};
  const position = data['Position'] || data['Job Title'] || '';
  const select = this.page.locator('#fleet-registration-page-position, select[name*="position" i], select[id*="position" i]').first();
  if ((await select.count()) > 0) {
    await select.scrollIntoViewIfNeeded().catch(() => {});
    const options = await select.locator('option').allTextContents();
    const match = position
      ? (options.find(o => o.trim().toLowerCase().includes(position.toLowerCase())) || null)
      : null;
    if (match) {
      await select.selectOption({ label: match.trim() });
    } else if (options.length > 1) {
      await select.selectOption({ index: 1 });
    }
    const selected = await select.inputValue();
    console.log(`📋 Selected Position: ${selected}`);
  }
  await this.page.waitForTimeout(300);
});

When('the user inputs a valid ABN', async function () {
  const data = this.fleetData?.[0] || {};
  const abn = String(data['ABN'] || data['Abn'] || '12345678901');
  const field = this.page.locator('#fleet-registration-page-abn, input[name*="abn" i], input[id*="abn" i]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(abn);
    console.log(`📋 Entered ABN: ${abn}`);
  }
});

When('the user enters Company Name', async function () {
  const data = this.fleetData?.[0] || {};
  const company = data['Company Name'] || data['Company'] || 'Test Company Pty Ltd';
  const field = this.page.locator('#fleet-registration-page-company-name, input[name*="company" i], input[id*="company" i]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(company);
    console.log(`📋 Entered Company Name: ${company}`);
  }
});

When('the user selects a Purchase Category', async function () {
  const data = this.fleetData?.[0] || {};
  const category = data['Purchase Category'] || data['Category'] || '';
  const select = this.page.locator('#fleet-registration-page-purchase-category, select[name*="purchase" i], select[id*="purchase" i], select[name*="category" i]').first();
  if ((await select.count()) > 0) {
    await select.scrollIntoViewIfNeeded().catch(() => {});
    const options = await select.locator('option').allTextContents();
    const match = category
      ? (options.find(o => o.trim().toLowerCase().includes(category.toLowerCase())) || null)
      : null;
    if (match) {
      await select.selectOption({ label: match.trim() });
    } else if (options.length > 1) {
      await select.selectOption({ index: 1 });
    }
    const selected = await select.inputValue();
    console.log(`📋 Selected Purchase Category: ${selected}`);
  }
  await this.page.waitForTimeout(300);
});

When('the user selects an Industry', async function () {
  const data = this.fleetData?.[0] || {};
  const industry = data['Industry'] || '';
  const select = this.page.locator('#fleet-registration-page-industry, select[name*="industry" i], select[id*="industry" i]').first();
  if ((await select.count()) > 0) {
    await select.scrollIntoViewIfNeeded().catch(() => {});
    const options = await select.locator('option').allTextContents();
    const match = industry
      ? (options.find(o => o.trim().toLowerCase().includes(industry.toLowerCase())) || null)
      : null;
    if (match) {
      await select.selectOption({ label: match.trim() });
    } else if (options.length > 1) {
      await select.selectOption({ index: 1 });
    }
    const selected = await select.inputValue();
    console.log(`📋 Selected Industry: ${selected}`);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters an address', async function () {
  const data = this.ownershipData?.[0] || this.fleetData?.[0] || {};
  const address = data['Address'] || data['Street Address'] || '123 Test Street';
  // Fleet uses #fleet-registration-page-address; Ownership uses #ownership-page-page-address
  const field = this.page.locator('#ownership-page-page-address, input[name="Address__Street__s"], #fleet-registration-page-address, input[name*="address" i]:not([type="email"]):not([id*="postcode" i]):not([id*="email" i])').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(address);
    console.log(`📋 Entered Address: ${address}`);
  }
});

When('the user enters a suburb', async function () {
  const data = this.fleetData?.[0] || {};
  const suburb = data['Suburb'] || data['City'] || 'Sydney';
  const field = this.page.locator('#fleet-registration-page-suburb, input[name*="suburb" i], input[id*="suburb" i], input[name*="city" i]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(suburb);
    console.log(`📋 Entered Suburb: ${suburb}`);
  }
});

When('the user enters a stage', async function () {
  // "stage" in the feature file refers to the State/Territory dropdown
  const data = this.fleetData?.[0] || {};
  const state = data['State'] || data['Stage'] || data['Territory'] || 'NSW';
  const select = this.page.locator('#fleet-registration-page-state, select[name*="state" i], select[id*="state" i]').first();
  if ((await select.count()) > 0) {
    await select.scrollIntoViewIfNeeded().catch(() => {});
    const options = await select.locator('option').allTextContents();
    const match = options.find(o => o.trim().toUpperCase() === state.toUpperCase())
      || options.find(o => o.trim().toLowerCase().includes(state.toLowerCase()));
    if (match) {
      await select.selectOption({ label: match.trim() });
    } else if (options.length > 1) {
      await select.selectOption({ index: 1 });
    }
    const selected = await select.inputValue();
    console.log(`📋 Selected State: ${selected}`);
  } else {
    // Some implementations use a text input for state
    const field = this.page.locator('input[name*="state" i], input[id*="state" i]').first();
    if ((await field.count()) > 0) {
      await field.fill(state);
      console.log(`📋 Entered State: ${state}`);
    }
  }
});

When('the user enters a Postcode', async function () {
  const data = this.fleetData?.[0] || {};
  const postcode = String(data['Postcode'] || data['Post Code'] || '2000');
  const field = this.page.locator('#fleet-registration-page-postcode, input[name*="postcode" i], input[id*="postcode" i], input[name*="zip" i]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(postcode);
    console.log(`📋 Entered Postcode: ${postcode}`);
  }
});

When('the user enters Fleet Size', async function () {
  const data = this.fleetData?.[0] || {};
  const fleetSize = String(data['Fleet Size'] || data['Number of Vehicles'] || '10');
  // Use ONLY the exact ID and field name — do NOT use input[id*="fleet" i] as it matches
  // ALL fleet-registration-page-* fields (first-name, last-name, etc.) and .first() would
  // fill the wrong field.
  const field = this.page.locator('#fleet-registration-page-fleet-size, input[name="Fleet_Size__c"]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(fleetSize);
    console.log(`📋 Entered Fleet Size: ${fleetSize}`);
  } else {
    console.warn('⚠️  Fleet Size field not found');
  }
});

When('the user enters Vehicle Replacement Policy in months', async function () {
  const data = this.fleetData?.[0] || {};
  const months = String(
    data['Vehicle Replacement Policy - in months'] ||
    data['Replacement Months'] || data['Months'] || '24'
  );
  const field = this.page.locator(
    '#fleet-registration-page-replacement-months, ' +
    'input[name*="month" i], input[id*="month" i], input[name*="replacement" i][name*="month" i]'
  ).first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(months);
    console.log(`📋 Entered Vehicle Replacement Months: ${months}`);
  }
});

When('the user enters Vehicle Replacement Policy in kms', async function () {
  const data = this.fleetData?.[0] || {};
  const kms = String(
    data['Vehicle Replacement Policy - in kms'] ||
    data['Replacement Kms'] || data['Kms'] || '40000'
  );
  const field = this.page.locator(
    '#fleet-registration-page-replacement-kms, ' +
    'input[name*="km" i], input[id*="km" i]'
  ).first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(kms);
    console.log(`📋 Entered Vehicle Replacement Kms: ${kms}`);
  }
});

When('the user leaves the last name blank', async function () {
  const _f = this.page.locator('#fleet-registration-page-last-name').first();
  if ((await _f.count()) > 0) {
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill('');
    console.log('📋 Left Last Name field empty');
  } else {
    console.log('⚠️  Last Name field not found — skipping');
  }
});

When('the user leave a phone number blank', async function () {
  const _f = this.page.locator('#fleet-registration-page-phone-number').first();
  if ((await _f.count()) > 0) {
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill('');
    console.log('📋 Left Phone Number field empty');
  } else {
    console.log('⚠️  Phone Number field not found — skipping');
  }
});

When('the user enters a phone number', async function () {
  const data = this.ownershipData?.[0] || this.fleetData?.[0] || {};
  let phone = String(data['Phone'] || data['Phone Number'] || '0400000000');
  if (/^\d{9}$/.test(phone)) phone = '0' + phone;
  // Fleet uses #fleet-registration-page-phone-number; Ownership uses #ownership-page-phone-number
  const field = this.page.locator('#ownership-page-phone-number, input[name="MobilePhone__c"], #fleet-registration-page-phone-number, input[name*="phone" i], input[id*="phone" i], input[type="tel"]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(phone);
    console.log(`📋 Entered Phone: ${phone}`);
  }
});

When('the user leaves Fleet Size blank', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user leaves Fleet Size blank`);
  assert.ok(content.length > 0, 'the user leaves Fleet Size blank');
});

When('the user leaves Vehicle Replacement Policy in months blank', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user leaves Vehicle Replacement Policy in months blank`);
  assert.ok(content.length > 0, 'the user leaves Vehicle Replacement Policy in months blank');
});

When('the user leaves Vehicle Replacement Policy in kms blank', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user leaves Vehicle Replacement Policy in kms blank`);
  assert.ok(content.length > 0, 'the user leaves Vehicle Replacement Policy in kms blank');
});
