// @protected
/**
 * Auto-Generated Step Definitions for: Fleet Registration
 * Source: fleet-registration.feature
 * Generated: 2026-04-09T01:04:52.865Z
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user navigates to the page', async function () {
  const pageKey = 'the';
  const url = (this.pageUrls && this.pageUrls[pageKey]) || '';
  console.log(`📋 Navigating to ${pageKey}: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

Then('the fleet registration page should load without errors', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the fleet registration page should load without errors`);
  assert.ok(content.length > 0, 'the fleet registration page should load without errors');
});

Then('the page title should contain {string}', async function (param) {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  assert.ok(content.length > 0, 'the page title should contain {string}');
});

Then('Hyundai branding should be visible', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'Hyundai branding should be visible');
});

Then('the user should see business details fields', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'the user should see business details fields');
});

Then('the user should see contact person details fields', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'the user should see contact person details fields');
});

Then('the user should see fleet size selection', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'the user should see fleet size selection');
});

Then('the user should see industry selection options', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'the user should see industry selection options');
});

Then('the user should see a submit button', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'the user should see a submit button');
});

When('the user submits the fleet registration form', async function () {
  // The fleet registration page has multiple button[type="submit"] elements:
  //   1. button.search-submit  — hidden, in the site search form (WRONG — submits search)
  //   2. button.btn.submit     — visible, "Submit enquiry", in form.fleet-registration (CORRECT)
  // DO NOT use a broad selector like 'button[type="submit"]'.first() — that grabs the
  // hidden search button first in DOM order, submitting the wrong form.
  // Fleet form is a GET form (not POST) — submission causes a same-URL page navigation
  // that returns the thank-you message inline.
  const SUBMIT_SEL = 'form.fleet-registration button[type="submit"], button.btn.submit';
  const submitBtn = this.page.locator(SUBMIT_SEL).first();
  if ((await submitBtn.count()) > 0) {
    await submitBtn.scrollIntoViewIfNeeded().catch(() => {});
    await submitBtn.waitFor({ state: 'visible', timeout: 10000 });
    // Trigger click and wait for the resulting page load together
    await Promise.all([
      this.page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => {}),
      this.page.click(SUBMIT_SEL, { timeout: 10000 }),
    ]);
    console.log('📋 Fleet registration form submitted');
  } else {
    console.warn('⚠️  Submit button not found — attempting form.submit()');
    await this.page.evaluate(() => {
      const form = document.querySelector('form.fleet-registration, form[action*="fleet"]');
      if (form) form.submit();
    });
    await this.page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => {});
  }
  await this.page.waitForTimeout(2000);
});

When('the user enters an invalid mobile number', async function () {
  const input = this.page.locator('input:visible').first();
  await input.waitFor({ state: 'visible', timeout: 10000 });
  await input.clear();
  console.log('📋 Cleared input field');
  await this.page.waitForTimeout(500);
});

Then('a mobile number validation error message should be displayed', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'a mobile number validation error message should be displayed');
});

When('the user enters valid business details', async function () {
  const input = this.page.locator('input:visible').first();
  await input.waitFor({ state: 'visible', timeout: 10000 });
  await input.clear();
  console.log('📋 Cleared input field');
  await this.page.waitForTimeout(500);
});

When('the user selects a fleet size', async function () {
  const dropdown = this.page.locator('select:visible').first();
  if ((await dropdown.count()) > 0) {
    const options = await dropdown.locator('option').allTextContents();
    if (options.length > 1) await dropdown.selectOption({ index: 1 });
  }
  await this.page.waitForTimeout(500);
});

When('the user selects an industry type', async function () {
  const dropdown = this.page.locator('select:visible').first();
  if ((await dropdown.count()) > 0) {
    const options = await dropdown.locator('option').allTextContents();
    if (options.length > 1) await dropdown.selectOption({ index: 1 });
  }
  await this.page.waitForTimeout(500);
});

Then('the user should be informed that a fleet representative will contact them', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user should be informed that a fleet representative will contact them`);
  assert.ok(content.length > 0, 'the user should be informed that a fleet representative will contact them');
});

When('the user inputs {string} as the fleet size', async function (param) {
  const input = this.page.locator('input:visible').first();
  await input.waitFor({ state: 'visible', timeout: 10000 });
  await input.clear();
  await input.fill(param);
  console.log(`📋 Entered "${param}"`);
  await this.page.waitForTimeout(500);
});

When('the user submits the fleet registration form with valid details', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user submits the fleet registration form with valid details`);
  assert.ok(content.length > 0, 'the user submits the fleet registration form with valid details');
});

Then('the registration should be accepted', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the registration should be accepted`);
  assert.ok(content.length > 0, 'the registration should be accepted');
});

Then('the lead should be categorized as a small fleet enquiry', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the lead should be categorized as a small fleet enquiry`);
  assert.ok(content.length > 0, 'the lead should be categorized as a small fleet enquiry');
});

When('a system error occurs', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: a system error occurs`);
  assert.ok(content.length > 0, 'a system error occurs');
});

Then('a generic error message should be displayed', async function () {
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'a generic error message should be displayed');
});

Then('the user should be advised to try again later', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the user should be advised to try again later`);
  assert.ok(content.length > 0, 'the user should be advised to try again later');
});

Then('all form fields should have associated labels', async function () {
  const inputs = this.page.locator('input:visible');
  const count = await inputs.count();
  let accessibleCount = 0;
  for (let i = 0; i < Math.min(count, 10); i++) {
    const input = inputs.nth(i);
    const id = await input.getAttribute('id').catch(() => null);
    const ariaLabel = await input.getAttribute('aria-label').catch(() => null);
    const placeholder = await input.getAttribute('placeholder').catch(() => null);
    if (id || ariaLabel || placeholder) accessibleCount++;
  }
  assert.ok(accessibleCount > 0 || count === 0, 'Labels should be associated with inputs');
});

Then('validation error messages should be accessible to screen readers', async function () {
  await this.page.waitForTimeout(2000);
  const errors = this.page.locator('[class*="error"], [class*="validation"], [role="alert"], span.error');
  let found = false;
  for (let i = 0; i < Math.min(await errors.count(), 10); i++) {
    if (await errors.nth(i).isVisible().catch(() => false)) { found = true; break; }
  }
  assert.ok(found, 'validation error messages should be accessible to screen readers');
});

Then('the page should be operable using keyboard navigation only', async function () {
  for (let i = 0; i < 10; i++) {
    await this.page.keyboard.press('Tab');
    await this.page.waitForTimeout(200);
  }
  console.log('📋 Navigated through page using Tab key');
});

When('the user successfully submits the fleet registration form', async function () {
  await this.page.waitForTimeout(3000);
  const success = this.page.locator('[class*="thank"], [class*="success"], [class*="confirm"]').first();
  const visible = (await success.count()) > 0 && (await success.isVisible().catch(() => false));
  const url = this.page.url();
  assert.ok(visible || /thank|success|confirm/i.test(url), 'the user successfully submits the fleet registration form');
});

Then('the fleet registration submission event should be tracked', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the fleet registration submission event should be tracked`);
  assert.ok(content.length > 0, 'the fleet registration submission event should be tracked');
});

Then('the lead details should be sent to the CRM system', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: the lead details should be sent to the CRM system`);
  assert.ok(content.length > 0, 'the lead details should be sent to the CRM system');
});
