// @protected
/**
 * Auto-Generated Step Definitions for: Genesis Forms - Submit without Last Name should prevent submission
 * Source: genesis_lastname_empty.feature
 * Generated: 2026-04-09T02:29:07.446Z
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { When } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import {
  clickSubmitAndCapture,
  fillGenesisFieldsFromDataTable,
} from '../support/genesisFormHelpers.js';

When('I fill in all required fields except Last Name', async function (dataTable) {
  this.genesisFilledData = await fillGenesisFieldsFromDataTable(this.page, dataTable, { excludeFields: ['Last Name'] });
});

When('I click Submit', async function () {
  this.genesisSubmissionState = await clickSubmitAndCapture(this.page, 'Last Name');
  assert.ok(this.genesisSubmissionState.submitFound, 'Expected a visible submit button, but none was found');
});
