// @protected
/**
 * Auto-Generated Step Definitions for: Genesis Forms - Last Name Required Field Validation
 * Source: genesis_lastname_validation.feature
 * Generated: 2026-04-09T01:34:58.099Z
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import {
  clickSubmitAndCapture,
  collectVisibleErrorTexts,
  collectFieldValidationEvidence,
  fillGenesisFieldsFromDataTable,
  navigateToGenesisForm,
  submissionWasPrevented,
  textIsVisible,
} from '../support/genesisFormHelpers.js';

Given('I am a user on the Genesis website', async function () {
  assert.ok(true, 'Genesis browser session is available');
});

Given('I navigate to the BATD form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

When('I leave all fields empty', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: I leave all fields empty`);
  assert.ok(content.length > 0, 'I leave all fields empty');
});

When('I click the Submit button', async function () {
  this.genesisSubmissionState = await clickSubmitAndCapture(this.page, 'Last Name');
  assert.ok(this.genesisSubmissionState.submitFound, 'Expected a visible submit button, but none was found');
});

Then('the form should prevent submission', async function () {
  const state = await submissionWasPrevented(this.page, this.genesisSubmissionState);
  this.genesisSubmissionState = state;

  assert.ok(
    state.prevented,
    `Expected submission to be prevented. submitFound=${state.submitFound}, successVisible=${state.successVisible}, ` +
      `successText=${JSON.stringify(state.successText)}, formVisible=${state.formVisible}, ` +
      `urlBefore=${state.urlBefore}, urlAfter=${state.urlAfter}`
  );
});

Then('I should see a validation error on the {string} field', async function (value) {
  const evidence = await collectFieldValidationEvidence(this.page, value);
  assert.ok(evidence.fieldFound, `Expected to find the "${value}" field on the form`);
  assert.ok(
    evidence.hasVisibleError,
    `Expected a visible validation error for "${value}". ` +
      `describedByTexts=${JSON.stringify(evidence.describedByTexts)}, ` +
      `nearbyErrors=${JSON.stringify(evidence.nearbyErrors)}, ` +
      `inputState=${JSON.stringify(evidence.inputState)}`
  );
});

Then('I should NOT see the {string} error message', async function (param) {
  const visibility = await textIsVisible(this.page, param);
  assert.equal(visibility.visible, false, `Did not expect to see error message "${param}"`);
});

Then('I should NOT see the {string} success message', async function (param) {
  const visibility = await textIsVisible(this.page, param);
  assert.equal(visibility.visible, false, `Did not expect to see success message "${param}"`);
});

Given('I navigate to the General Enquiry form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

Given('I navigate to the Download E-Brochure form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

Given('I navigate to the Book a Service form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

Given('I navigate to the Subscribe form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

Given('I navigate to the RYI form {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

When('I fill in all required fields EXCEPT Last Name', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: I fill in all required fields EXCEPT Last Name`);
  assert.ok(content.length > 0, 'I fill in all required fields EXCEPT Last Name');
});

When('I fill in all required fields', async function (dataTable) {
  this.genesisFilledData = await fillGenesisFieldsFromDataTable(this.page, dataTable);
});

When('the user selects {string} from {string} dropdown', async function (optionLabel, fieldLabel) {
  const page = this.page;
  console.log(`📋 Step: select "${optionLabel}" from "${fieldLabel}" dropdown`);

  // Dismiss cookie banner if present.
  for (const sel of ['#onetrust-accept-btn-handler', 'button:has-text("Accept All")', 'button:has-text("I agree")']) {
    const b = page.locator(sel).first();
    if ((await b.count()) > 0 && (await b.isVisible().catch(() => false))) {
      await b.click({ force: true }).catch(() => {});
      await page.waitForTimeout(300);
      break;
    }
  }

  // Map known field labels to Genesis dropdown-container data-dropdown-name values.
  const fieldLower = fieldLabel.toLowerCase();
  let containerName = null;
  if (/sub.?enquiry|enquiry.?type|lead.?type/.test(fieldLower)) containerName = 'leadType';
  else if (/purchase|time/.test(fieldLower)) containerName = 'purchaseTimeline';
  else if (/vehicle|model/.test(fieldLower)) containerName = 'modelName';

  // Build a scoped container locator (Genesis cm-select widget).
  let container = null;
  if (containerName) {
    const all = page.locator(`.dropdown-container[data-dropdown-name="${containerName}"]`);
    const count = await all.count();
    for (let i = 0; i < count; i++) {
      const c = all.nth(i);
      if (await c.isVisible().catch(() => false)) {
        container = c;
        break;
      }
    }
  }

  // Fallback: locate container by visible placeholder text containing the field label keywords.
  if (!container) {
    const all = page.locator('.dropdown-container');
    const count = await all.count();
    for (let i = 0; i < count; i++) {
      const c = all.nth(i);
      if (!(await c.isVisible().catch(() => false))) continue;
      const txt = ((await c.innerText().catch(() => '')) || '').toLowerCase();
      const labelKeywords = fieldLower.split(/\s+/).filter((w) => w.length > 3);
      const matches = labelKeywords.some((kw) => txt.includes(kw));
      if (matches) { container = c; break; }
    }
  }

  if (container) {
    const trigger = container.locator('a.cm-select__placeholder, .cm-select__placeholder').first();
    await trigger.scrollIntoViewIfNeeded().catch(() => {});
    await trigger.click({ force: true }).catch(async () => {
      await trigger.evaluate((el) => el.click()).catch(() => {});
    });
    await page.waitForTimeout(400);

    const optionLocators = [
      container.locator(`a[role="option"]:has-text("${optionLabel}")`).first(),
      container.locator(`li[data-value="${optionLabel}" i] a[role="option"]`).first(),
      container.locator(`li:has-text("${optionLabel}") a[role="option"]`).first(),
      container.locator(`a[role="option"]`, { hasText: optionLabel }).first(),
    ];
    for (const opt of optionLocators) {
      if ((await opt.count()) > 0 && (await opt.isVisible().catch(() => false))) {
        await opt.click({ force: true }).catch(async () => {
          await opt.evaluate((el) => el.click()).catch(() => {});
        });
        await page.waitForTimeout(200);
        return;
      }
    }
    throw new Error(`Genesis dropdown opened for "${fieldLabel}" but option "${optionLabel}" not found in container`);
  }

  // Final fallback: world-level generic helper.
  if (typeof this.selectDropdown === 'function') {
    const ok = await this.selectDropdown(fieldLabel, optionLabel).catch(() => false);
    if (ok) return;
  }

  throw new Error(`Could not find dropdown for "${fieldLabel}"`);
});

Then('the form should submit successfully', async function () {
  await this.page.waitForTimeout(3000);
  const success = this.page.locator('[class*="thank"], [class*="success"], [class*="confirm"]').first();
  const visible = (await success.count()) > 0 && (await success.isVisible().catch(() => false));
  const url = this.page.url();
  assert.ok(visible || /thank|success|confirm/i.test(url), 'the form should submit successfully');
});

Then('I should see the {string} success message', async function (param) {
  const visibility = await textIsVisible(this.page, param);
  assert.equal(visibility.visible, true, `Expected to see success message "${param}"`);
});

Then('I should NOT see any validation errors', async function () {
  const errorTexts = await collectVisibleErrorTexts(this.page);
  assert.equal(
    errorTexts.length,
    0,
    `Did not expect visible validation errors, but found: ${errorTexts.join(' | ')}`
  );
});
