// @protected
/**
 * Auto-Generated Step Definitions for: Genesis Forms - Submit with all fields including Last Name shows Thank you
 * Source: genesis_all_fields_filled.feature
 * Generated: 2026-04-09T02:43:19.230Z
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import {
  detectDownloadBrochureFiles,
  waitForDownloadBrochureFiles,
  waitForVisibleText,
} from '../support/genesisFormHelpers.js';

Then('I should see {string} success message', async function (param) {
  const visibility = await waitForVisibleText(this.page, param, 15000);
  if (visibility.visible) {
    assert.equal(visibility.visible, true, `Expected to see success message "${param}"`);
    return;
  }

  const isDownloadBrochure = /#downloadebrochure/i.test(this.page.url());
  if (isDownloadBrochure) {
    const selectedModel = this.genesisFilledData?.['Vehicle Selection'] || this.genesisFilledData?.['vehicle selection'] || '';
    const brochureFiles = await waitForDownloadBrochureFiles(this.page, selectedModel, 15000);
    assert.equal(
      brochureFiles.visible,
      true,
      `Expected brochure files for selected model "${selectedModel}", but found: ${brochureFiles.items.join(' | ')}`
    );
    return;
  }

  // Scroll to the form/status area so the screenshot captures any error message
  // that appears at the bottom of the form (e.g. "Sorry, something went wrong")
  await this.page.evaluate(() => {
    const statusEl = document.querySelector(
      '[class*="sorry"], [class*="error"], [class*="status"], [class*="wrong"], form#form-ryi-form, .cp-ryi__form'
    );
    if (statusEl) {
      statusEl.scrollIntoView({ behavior: 'instant', block: 'center' });
    } else {
      window.scrollTo(0, document.body.scrollHeight);
    }
  }).catch(() => {});
  await this.page.waitForTimeout(500);

  assert.equal(visibility.visible, true, `Expected to see success message "${param}"`);
});
