// @protected
/**
 * Auto-Generated Step Definitions for: Genesis Forms - Submit with all fields empty shows Last Name validation error
 * Source: genesis_all_fields_empty.feature
 * Generated: 2026-04-09T01:45:51.444Z
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import {
  clickSubmitAndCapture,
  collectFieldValidationEvidence,
  navigateToGenesisForm,
  textIsVisible,
} from '../support/genesisFormHelpers.js';

Given('I navigate to {string}', async function (url) {
  await navigateToGenesisForm(this.page, url);
});

When('I leave all fields empty and click Submit', async function () {
  this.genesisSubmissionState = await clickSubmitAndCapture(this.page, 'Last Name');
  assert.ok(this.genesisSubmissionState.targetFieldFound, 'Expected the Last Name field to be visible before submit');
  assert.ok(this.genesisSubmissionState.submitFound, 'Expected a visible submit button, but none was found');
});

Then('I should see validation error on {string}', async function (fieldName) {
  const evidence = await collectFieldValidationEvidence(this.page, fieldName);
  this.genesisValidationEvidence = evidence;

  assert.ok(evidence.fieldFound, `Expected to find the "${fieldName}" field on the form`);
  assert.ok(
    evidence.hasVisibleError,
    `Expected a visible validation error for "${fieldName}". ` +
      `describedByTexts=${JSON.stringify(evidence.describedByTexts)}, ` +
      `nearbyErrors=${JSON.stringify(evidence.nearbyErrors)}, ` +
      `inputState=${JSON.stringify(evidence.inputState)}`
  );
});

Then('I should NOT see {string}', async function (text) {
  const visibility = await textIsVisible(this.page, text);
  assert.equal(
    visibility.visible,
    false,
    `Did not expect to see "${text}", but found: ${visibility.matches.join(' | ')}`
  );
});
