// @protected
/**
 * Auto-Generated Step Definitions for: Genesis RYI - Verify status code in API Payload
 * Source: GenesisRYI.feature
 * Generated: 2026-04-14T03:28:24.713Z
 * Target URL: https://stage.hyundai.com.au/au/en/cars/eco/elexio-ryi
 *
 * DOM Field Map:
 *   "Title" → #Salutation
 *   "First Name" → #FirstName
 *   "Last Name" → #LastName
 *   "Email" → #Email
 *   "Mobile*" → #MobilePhone
 *   "State*" → #State
 *   "Postcode" → #PostalCode
 *   "When are you looking to purchase your next car?*" → #PurchaseIntentTimeFrame__c
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user navigates to Genesis RYI Page', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  const url = (this.pageUrls && (
    this.pageUrls['genesis ryi page'] ||
    this.pageUrls['genesis ryi'] ||
    Object.entries(this.pageUrls).find(([k]) => k.includes('genesis') && k.includes('ryi'))?.[1]
  ))
    || 'https://stage.genesis-motors.com.au/au/en/models/gv60-magma-teaser.html';
  console.log(`📋 Navigating to Genesis RYI Page: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

When('the user enters a postcode', async function () {
  const data = this.genesisRyiData?.[0] || {};
  const postcode = String(data['Postcode'] || data['Postal Code'] || data['Post Code'] || '2000');
  // Real DOM: id="inpCode1" name="postCode"
  const field = this.page.locator('#inpCode1, input[name="postCode"]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(postcode);
    console.log(`📋 Entered Postcode: ${postcode}`);
  }
});

When('the user selects Preferred Contact Method', async function () {
  const data = this.genesisRyiData?.[0] || {};
  const method = (data['Preferred Contact Method'] || data['Contact Method'] || 'Email').toLowerCase();
  // Real DOM: radio inputs with name="preferredContactMethod"
  // #methodCheck0 = Email, #methodCheck1 = Phone
  const targetId = method.includes('phone') ? '#methodCheck1' : '#methodCheck0';
  const radio = this.page.locator(targetId).first();
  if ((await radio.count()) > 0) {
    const parentLabel = radio.locator('xpath=ancestor::label[1]').first();
    if ((await parentLabel.count()) > 0) {
      await parentLabel.click({ force: true }).catch(async () => { await radio.evaluate(el => el.click()); });
    } else {
      await radio.evaluate(el => el.click());
    }
    console.log(`📋 Selected Preferred Contact Method: ${method}`);
  }
  await this.page.waitForTimeout(300);
});

When('the user leaves last name blank', async function () {
  // Real DOM: id="lastName" name="lastName"
  const field = this.page.locator('#lastName, input[name="lastName"]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill('');
    console.log('📋 Left Last Name blank');
  } else {
    console.log('⚠️ Last Name field not found');
  }
});

When('the user submits the RYI form without completing required fields', async function () {
  // Real DOM: form#form-ryi-form, submit button has class btn btn-primary
  const _sb = this.page.locator('#form-ryi-form button[type="submit"], .cp-ryi__form button[type="submit"]').first();
  if ((await _sb.count()) > 0) {
    await _sb.scrollIntoViewIfNeeded().catch(() => {});
    await _sb.evaluate(el => el.click()).catch(async () => { await _sb.click({ force: true }).catch(() => {}); });
    console.log('📋 Submitted RYI form without filling required fields');
  }
  await this.page.waitForTimeout(3000);
});

Then('the RYI form should not be submitted', async function () {
  await this.page.waitForTimeout(2000);
  const _el = this.page.locator('.thank-you, [class*="thank-you"], [class*="success"], [class*="confirmation"]').first();
  const _vis = (await _el.count()) > 0 && (await _el.isVisible().catch(() => false));
  const _url = this.page.url();
  assert.ok(!_vis && !/thank|confirm|success/i.test(_url), 'Form should NOT be submitted (no success message or redirect)');
});

When('the user enters a last name', async function () {
  const data = this.genesisRyiData?.[0] || {};
  const lastName = data['Last Name'] || data['LastName'] || 'Smith';
  // Real DOM: id="lastName" name="lastName"
  const field = this.page.locator('#lastName, input[name="lastName"]').first();
  if ((await field.count()) > 0) {
    await field.scrollIntoViewIfNeeded().catch(() => {});
    await field.fill(lastName);
    console.log(`📋 Entered Last Name: ${lastName}`);
  }
});

When('the user doesnt select the privacy consent checkbox', async function () {
  // Real DOM: id="agreeCheck" name="termsAgreement" — ensure it stays unchecked
  const cb = this.page.locator('#agreeCheck, input[name="termsAgreement"]').first();
  if ((await cb.count()) > 0) {
    const isChecked = await cb.isChecked().catch(() => false);
    if (isChecked) {
      const lbl = cb.locator('xpath=ancestor::label[1]').first();
      if ((await lbl.count()) > 0) {
        await lbl.click({ force: true }).catch(async () => { await cb.evaluate(el => el.click()); });
      } else {
        await cb.evaluate(el => el.click());
      }
    }
    console.log('📋 Privacy consent left unchecked');
  }
});
