/**
 * Auto-Generated Step Definitions for: user visit on hyundai CPC page
 * Source: jajatest.feature
 * Generated: 2026-06-24T05:44:26.806Z
 * Target URL: https://dev.hyundai.com.au/au/en/shop/calculator/
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user is in this link {string}', async function (param) {
  // "the user is in this link <URL>" — a human would open that URL in the browser.
  const url = String(param || '').trim();
  assert.ok(/^https?:\/\//i.test(url), `Expected a navigable URL but got: "${url}"`);
  console.log(`📋 Step: the user is in this link → ${url}`);

  // Navigate only if we are not already on the requested page (the scenario
  // repeats this step via Background + Scenario; avoid a redundant reload).
  if (this.page.url().replace(/\/$/, '') !== url.replace(/\/$/, '')) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  }
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(500);

  const content = await this.page.content();
  assert.ok(content.length > 0, 'the page failed to load any content');
});

Then('the user should see the {string} title', async function (param) {
  // The title text comes from the Gherkin step — use it, don't hardcode it.
  const _name = String(param || '').trim();
  await this.page.waitForTimeout(1500);
  let _vis = false;

  // Build a regex from the expected title (escape regex metacharacters such as
  // the trailing period in "Configure your Hyundai.").
  const _re = new RegExp(_name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');

  // 1) Preferred: match a real heading element (h1–h6 or role="heading").
  //    On the CPC page the title renders as <h1>Configure your Hyundai.</h1>.
  if (_name) {
    _vis = await this.page
      .getByRole('heading', { name: _re })
      .first()
      .isVisible()
      .catch(() => false);
  }

  // 2) Fallback: any visible element containing the title text.
  if (!_vis && _name) {
    _vis = await this.page.getByText(_re).first().isVisible().catch(() => false);
  }

  assert.ok(
    _vis,
    `Expected to see the "${_name}" title on the page, but it was not visible.`
  );
});
