/**
 * Auto-Generated Step Definitions for: Hyundai Australia Build & Price Navigation
 * Source: Janki.feature
 * Generated: 2026-05-12T06:16:31.759Z
 * Target URL: https://stage.hyundai.com.au/au/en
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('user navigates to Home', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: home
  const _pageKeys = ["home"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan against keys
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
    if (!url) {
      // Slug scan against URL paths — handles "customer care" → ".../customer-care/..."
      const _slugEntry = Object.entries(this.pageUrls).find(([, u]) => {
        try {
          const _p = new URL(u).pathname.toLowerCase();
          return _pageKeys.some(pk => pk && (_p.includes(pk.replace(/\s+/g, '-')) || _p.includes(pk.replace(/\s+/g, ''))));
        } catch { return false; }
      });
      if (_slugEntry) url = _slugEntry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en';
  console.log(`📋 Navigating to home: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

When('user clicks on the first {string} button', async function (buttonName) {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks
  await this.clickButton(buttonName);
  await this.page.waitForTimeout(1000);
});

Then('user should be redirected to a URL containing {string}', async function (param) {
  await this.page.waitForTimeout(2000);
  const url = this.page.url();
  console.log(`📋 Current URL: ${url}`);
  assert.ok(url, 'URL should be available');
});
