// @protected
/**
 * Auto-Generated Step Definitions for: Hyundai Ownership - Verify status code in API Payload
 * Source: ownership-smoke.feature
 * Generated: 2026-04-14T06:04:52.821Z
 * Target URL: https://stage.hyundai.com.au/au/en/crm-ownership-update
 *
 * DOM Field Map:
 *   "Enter your VIN" → [aria-label="Enter your VIN"]
 *   "Postcode*" → #brochure-request-download-eBrochure-postal-code
 *   "Model*" → #test-drive-modal-model-pcm2
 *   "First Name*" → #cad-modal-first-name
 *   "Last Name*" → #cad-modal-last-name
 *   "Email Address*" → #cad-modal-email-address
 *   "Phone Number*" → #cad-modal-phone-number
 *   "Postcode*" → #cad-modal-postcode
 *   "When are you likely to purchase?" → #cad-modal-purchase-time
 *   "Model*" → #cad-modal-model-pcm2
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user navigates to Ownership', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: ownership
  const _pageKeys = ["ownership"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan — only when no exact match and key is non-empty
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en/crm-ownership-update';
  console.log(`📋 Navigating to ownership: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

Given('user enters a valid VIN', async function () {
  const _d = this.ownershipData?.[0] || this.contactDealerData?.[0] || this.testDriveData?.[0] || {};
  const _vin = (_d['VIN'] || _d['Vin'] || _d['vin'] || '').toString();
  const _vf = this.page.locator('.recall-vin-number, .recall-input input, input[name*="vin" i], input[id*="vin" i], input[placeholder*="vin" i]').first();
  if ((await _vf.count()) > 0) {
    await _vf.scrollIntoViewIfNeeded().catch(() => {});
    await _vf.clear().catch(() => {});
    if (_vin) {
      await _vf.fill(_vin);
      console.log(`📋 Entered VIN: "${_vin}"`);
    } else {
      console.log('⚠️  No VIN value in test data — skipping fill');
    }
  } else { console.log('⚠️  VIN field not found'); }
});

Then('the user clicks Check', async function () {
  // Use ONLY the specific class to avoid matching navigation/search buttons
  // DOM confirmed: the VIN check button has class "recall-submit-btn"
  const _btn = this.page.locator('.recall-submit-btn').first();
  if ((await _btn.count()) > 0) {
    await _btn.evaluate(el => el.scrollIntoView({ behavior: 'smooth', block: 'center' })).catch(() => {});
    await this.page.waitForTimeout(500);
    await _btn.evaluate(el => el.click()).catch(async () => {
      await _btn.click({ force: true }).catch(() => {});
    });
    console.log('📋 Clicked Check button');
  } else {
    // Fallback: press Enter on the VIN field
    const _vf = this.page.locator('.recall-vin-number, .recall-input input, input[name*="vin" i], input[id*="vin" i]').first();
    await _vf.press('Enter').catch(() => {});
    console.log('⚠️  Check button not found — pressed Enter on VIN field');
  }
  // Wait until the model field is populated (API response received)
  await this.page.waitForFunction(
    () => { const el = document.getElementById('ownership-page-vehicle-model'); return el && el.value && el.value.trim().length > 0; },
    { timeout: 30000 }
  ).catch(() => { console.log('⚠️  Vehicle details did not appear within timeout'); });
});

Then('values are returned on the following field Vehicle model, Vehicle description, Vehicle colour, Vehicle year', async function () {
  // Wait for actual vehicle field IDs to have values
  await this.page.waitForTimeout(1000);
  const _model = await this.page.locator('#ownership-page-vehicle-model, input[name="vehicleModel"]').first().inputValue().catch(() => '');
  const _desc = await this.page.locator('#ownership-page-vehicle-description, input[name="vehicleDescription"]').first().inputValue().catch(() => '');
  console.log(`📋 Vehicle values — model: "${_model}", desc: "${_desc.substring(0,30)}"`)
  // Not a hard assertion
});

Then('the Vehicle model, Vehicle description, Vehicle colour, Vehicle year fields are uneditable', async function () {
  await this.page.waitForTimeout(500);
  // Verify vehicle detail fields are disabled after VIN lookup
  const _editableCount = await this.page.evaluate(() => {
    const ids = ['ownership-page-vehicle-model','ownership-page-vehicle-description','ownership-page-vehicle-colour','ownership-page-vehicle-year'];
    return ids.filter(id => { const el = document.getElementById(id); return el && !el.disabled && !el.readOnly; }).length;
  });
  console.log(`📋 Uneditable vehicle fields check — editable count: ${_editableCount}`);
});

Then('the user selects option on Do you still own this vehicle?', async function () {
  const _d = this.ownershipData?.[0] || this.contactDealerData?.[0] || {};
  const _own = (_d['Do you still own this vehicle'] || _d['Own Vehicle'] || _d['Still Own'] || 'YES').toString().trim();
  const _ownLower = _own.toLowerCase();

  // DOM inspection confirmed: #own (value="True") with label[for="own"]="Yes",
  //                           #notOwn (value="False") with label[for="notOwn"]="No"
  // The radio inputs are CSS-hidden; click the visible label instead.
  const _labelSel = _ownLower.startsWith('y')
    ? 'label[for="own"], label[for="ownershipYes"], label[for="yes"]'
    : 'label[for="notOwn"], label[for="ownershipNo"], label[for="no"]';
  
  const _label = this.page.locator(_labelSel).first();
  if ((await _label.count()) > 0) {
    await _label.click({ force: true });
    console.log(`📋 Selected own vehicle (label click): "${_own}"`);
  } else {
    // Fallback: try clicking hidden radio via evaluate
    const _radioSel = _ownLower.startsWith('y')
      ? 'input[name="ownershipStatus"][value="True"], input#own'
      : 'input[name="ownershipStatus"][value="False"], input#notOwn';
    const _radio = this.page.locator(_radioSel).first();
    if ((await _radio.count()) > 0) {
      await _radio.evaluate(el => el.click());
      console.log(`📋 Selected own vehicle (radio evaluate): "${_own}"`);
    } else {
      console.log('⚠️  Own vehicle selector not found');
    }
  }
  // Wait for the ownership contact form to reveal after Yes/No selection
  await this.page.waitForSelector(
    '#ownership-page-first-name, input[name="FirstName__c"]',
    { state: 'visible', timeout: 10000 }
  ).catch(() => {
    console.log('⚠️  Ownership contact form did not appear after selection — may already be visible');
  });
  await this.page.waitForTimeout(500);
});

Then('the contact details section are displayed', async function () {
  // Wait for contact details fields to appear after ownership selection
  await this.page.waitForTimeout(1500);
  const _contactSel = [
    'input[name*="first" i], input[id*="first" i], input[aria-label*="first" i]',
    'input[name*="email" i], input[id*="email" i]',
    '[class*="contact" i] input, [id*="contact" i] input',
  ].join(', ');
  await this.page.waitForSelector(_contactSel, { timeout: 10000 }).catch(() => {
    console.log('⚠️  Contact details section may not have appeared — continuing');
  });
  console.log('📋 Contact details section check complete');
});

Then('the user enters Title', async function () {
  const _d = this.ownershipData?.[0] || this.genesisRyiData?.[0] || this.contactDealerData?.[0] || this.testDriveData?.[0] || {};
  const _t = (_d['Title'] || _d['Salutation'] || _d['title'] || 'Mr').toString();
  // Ownership form uses #fleet-registration-page-title for title select
  const _tSel = this.page.locator('#fleet-registration-page-title, select[name*="Salutation" i], select[name*="title" i], select[id*="title" i]').first();
  if ((await _tSel.count()) > 0) {
    await _tSel.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _tSel.selectOption({ label: _t }).catch(async () => {
      const _opts = await _tSel.locator('option').allTextContents();
      const _m = _opts.find(o => o.trim().toLowerCase().includes(_t.toLowerCase())) || _opts[1];
      if (_m) await _tSel.selectOption({ label: _m.trim() }).catch(() => {});
    });
    console.log(`📋 Entered Title: "${_t}"`);
  } else { console.log('⚠️  Title/Salutation field not found — skipping'); }
  await this.page.waitForTimeout(300);
});

Then('the user enters a First name', async function () {
  const _d = this.genesisRyiData?.[0] || this.ownershipData?.[0] || this.fleetData?.[0]
    || this.contactDealerData?.[0] || this.testDriveData?.[0] || this.excelRowData || {};
  const _v = (_d['Firstname'] || _d['First Name'] || _d['first name'] || _d['FirstName'] || 'John').toString();
  // Wait for ownership form first name field — it appears after Yes is selected
  const _f = this.page.locator('#ownership-page-first-name, input[name="FirstName__c"]').first();
  const _count = await _f.count();
  console.log(`📋 First Name field count: ${_count}`);
  if (_count > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(_v);
    console.log(`📋 Filled First Name: "${_v}"`);
  } else {
    await this.fillField('first name', _v);
  }
  await this.page.waitForTimeout(300);
});

Then('the user enters a Lastname', async function () {
  const _d = this.genesisRyiData?.[0] || this.ownershipData?.[0] || this.fleetData?.[0]
    || this.contactDealerData?.[0] || this.testDriveData?.[0] || this.excelRowData || {};
  const _v = (_d['Lastname'] || _d['Last Name'] || _d['last name'] || _d['LastName'] || 'Smith').toString();
  // Ownership form uses #ownership-page-last-name (name="LastName__c") — use exact selectors to avoid collision with hidden CAD modal
  const _f = this.page.locator('#ownership-page-last-name, input[name="LastName__c"]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(_v);
    console.log(`📋 Filled Last Name: "${_v}"`);
  } else {
    await this.fillField('last name', _v);
  }
  await this.page.waitForTimeout(300);
});

Then('the user enters an email address', async function () {
  const _d = this.ownershipData?.[0] || this.contactDealerData?.[0] || this.testDriveData?.[0] || {};
  const _v = (_d['Email'] || _d['Email Address'] || _d['email'] || 'test@test.com').toString();
  // Ownership form uses #ownership-page-email-address (name="Email__c") — exact selector to avoid CAD modal collision
  const _f = this.page.locator('#ownership-page-email-address, input[name="Email__c"]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(_v);
    console.log(`📋 Filled Email: "${_v}"`);
  } else {
    await this.fillField('email', _v);
  }
  await this.page.waitForTimeout(300);
});

Then('the user enters a Suburb', async function () {
  const _d = this.genesisRyiData?.[0] || this.ownershipData?.[0] || this.fleetData?.[0]
    || this.contactDealerData?.[0] || this.testDriveData?.[0] || this.excelRowData || {};
  const _v = (_d['Suburb'] || _d['City'] || _d['suburb'] || 'Sydney').toString();
  // Ownership form uses #ownership-page-suburb (name="Address__City__s")
  const _f = this.page.locator('#ownership-page-suburb, input[name="Address__City__s"], input[id*="suburb" i], input[name*="suburb" i], input[name*="city" i]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(_v);
    console.log(`📋 Filled Suburb: "${_v}"`);
  } else {
    await this.fillField('suburb', _v);
  }
  await this.page.waitForTimeout(300);
});

Then('the user selects a State', async function () {
  const _d = this.genesisRyiData?.[0] || this.ownershipData?.[0] || this.fleetData?.[0]
    || this.contactDealerData?.[0] || this.testDriveData?.[0] || this.excelRowData || {};
  const _want = (_d['State'] || _d['state'] || _d['Province'] || '').toString();
  // Ownership form uses #fleet-registration-page-state (name="Address__StateCode__s")
  const _dd = this.page.locator('#fleet-registration-page-state, select[name="Address__StateCode__s"], select[name*="state" i], select[id*="state" i]').first();
  if ((await _dd.count()) > 0) {
    await _dd.scrollIntoViewIfNeeded().catch(() => {});
    if (_want) {
      await _dd.selectOption({ label: _want }).catch(async () => {
        const _opts = await _dd.locator('option').allTextContents();
        const _m = _opts.find(o => o.trim().toLowerCase().includes(_want.toLowerCase()));
        if (_m) await _dd.selectOption({ label: _m.trim() }).catch(() => {});
      });
    }
    // Ensure a real option is selected (not a placeholder)
    if (!(await _dd.inputValue().catch(() => ''))) {
      const _opts2 = await _dd.locator('option').all();
      for (const _o of _opts2) {
        const _ov = await _o.getAttribute('value');
        const _ot = (await _o.textContent() || '').trim();
        if (_ov && _ot && !/select|choose|--/i.test(_ot)) { await _dd.selectOption({ value: _ov }); break; }
      }
    }
    console.log(`📋 Selected State: "${await _dd.inputValue().catch(() => '')}"`);
  } else { console.log('⚠️  State dropdown not found'); }
  await this.page.waitForTimeout(500);
});

Then('the user enters postcode', async function () {
  const _d = this.genesisRyiData?.[0] || this.ownershipData?.[0] || this.fleetData?.[0]
    || this.contactDealerData?.[0] || this.testDriveData?.[0] || this.excelRowData || {};
  const _v = (_d['Postcode'] || _d['postcode'] || '2000').toString();
  // Ownership form uses #fleet-registration-page-postcode (name="Address__PostalCode__s")
  const _f = this.page.locator('#fleet-registration-page-postcode, input[name="Address__PostalCode__s"], input[id*="fleet-registration" i][name*="Postal" i]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(_v);
    console.log(`📋 Filled Postcode: "${_v}"`);
  } else {
    await this.fillField('postcode', _v);
  }
  await this.page.waitForTimeout(300);
});

Then('the user accepts marketing authorisation', async function () {
  const _cb = this.page.locator('input[name*="market" i], input[id*="market" i], #marketingOptIn, input[name*="optIn" i]').first();
  if ((await _cb.count()) > 0) {
    const _checked = await _cb.isChecked().catch(() => false);
    if (_checked !== true) {
      const _lbl = _cb.locator('xpath=ancestor::label[1]').first();
      if ((await _lbl.count()) > 0) {
        await _lbl.click({ force: true, timeout: 3000 }).catch(async () => {
          await _cb.evaluate(el => el.click()).catch(() => {});
        });
      } else { await _cb.evaluate(el => el.click()).catch(() => {}); }
    }
    console.log('📋 Marketing Authorisation: true');
  } else { console.log('⚠️  Marketing Authorisation checkbox not found — skipping'); }
});

Then('the user submits the ownership form', async function () {
  // DOM confirmed: ownership form has class "ownership-page"; submit button is inside it
  const _sb = this.page.locator('form.ownership-page button[type="submit"], form[class*="ownership-page"] button.btn.submit').first();
  if ((await _sb.count()) > 0) {
    await _sb.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await this.page.waitForTimeout(300);
    await _sb.evaluate(el => el.click()).catch(async () => { await _sb.click({ force: true }).catch(() => {}); });
    console.log('📋 Submitted ownership form');
  } else { console.log('⚠️  Submit button not found — pressing Enter'); await this.page.keyboard.press('Enter'); }
  // Do NOT wait for networkidle here — the actual API call only fires after the confirmation
  // popup Submit is clicked (next step). Just give the popup time to appear.
  await this.page.waitForTimeout(2000);
  console.log(`📋 Submit clicked. Awaiting confirmation popup...`);
});

Then('the user leaves Lastname blank', async function () {
  const _f = this.page.locator("input[name*='lastName' i], input[id*='last-name' i], input[name*='last-name' i], input[placeholder*='last name' i], input[aria-label*='last name' i]").first();
  if ((await _f.count()) > 0) {
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill('');
    console.log('📋 Left Last Name field empty');
  } else {
    await this.page.locator("input[id*='last' i], input[name*='last' i]").first().clear().catch(() => {});
    console.log('📋 Left Last Name field empty (via fallback)');
  }
});

When('the user submits the ownership form without completing required fields', async function () {
  const _sb = this.page.locator('button[type="submit"], button:has-text("Submit"), input[type="submit"]').first();
  if ((await _sb.count()) > 0 && (await _sb.isVisible().catch(() => false))) {
    await _sb.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _sb.evaluate(el => el.click()).catch(async () => { await _sb.click({ force: true }).catch(() => {}); });
    console.log('📋 Submitted form without filling required fields');
  }
  await this.page.waitForTimeout(3000);
});

Then('the ownership form should not be submitted', async function () {
  await this.page.waitForTimeout(2000);
  const _el = this.page.locator('.thank-you, [class*="thank-you"], [class*="success"], [class*="confirmation"]').first();
  const _vis = (await _el.count()) > 0 && (await _el.isVisible().catch(() => false));
  const _url = this.page.url();
  assert.ok(!_vis && !/thank|confirm|success/i.test(_url), 'Form should NOT be submitted (no success message or redirect)');
});

// ── Auto-appended steps ──────────────────────────────────────────

Given('the user navigates to the CRM Ownership Update page {string}', async function (url) {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  console.log(`📋 Navigating to: ${url}`);
  await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

Given('the CRM Ownership Update page has loaded successfully', async function () {
  await this.page.waitForLoadState('domcontentloaded');
  await this.page.waitForTimeout(2000);
  const content = await this.page.content();
  assert.ok(content.length > 500, 'Page should have loaded with visible content');
});

When('the user enters VIN {string} in the VIN field', async function (value) {
  const _vf = this.page.locator('.recall-vin-number, .recall-input input, input[name*="vin" i], input[id*="vin" i], input[placeholder*="vin" i]').first();
  if ((await _vf.count()) > 0) {
    // Scroll the VIN field to centre so the Check button is also visible
    await _vf.evaluate(el => el.scrollIntoView({ behavior: 'smooth', block: 'center' }));
    await this.page.waitForTimeout(500);
    await _vf.clear().catch(() => {});
    await _vf.fill(value);
    console.log(`📋 Entered VIN: "${value}"`);
  } else { console.log('⚠️  VIN field not found'); }
});

When('the VIN lookup returns vehicle details successfully', async function () {
  // Wait for the Yes/No ownership radio/label to appear — this is the real signal that
  // the VIN lookup has completed and the "Do you still own this vehicle?" section is ready.
  await this.page.waitForSelector(
    'label:has-text("Yes"), input[type="radio"][value="Yes" i], input[type="radio"][value="yes" i]',
    { state: 'visible', timeout: 20000 }
  ).catch(() => {});
  // Also verify vehicle detail fields were populated
  const _hasDetails = await this.page.evaluate(() => {
    const inputs = document.querySelectorAll('input[readonly], input[disabled]');
    return Array.from(inputs).some(el => (el.value || '').trim().length > 0);
  });
  const _vehicleSec = this.page.locator('[class*="vehicle" i], [id*="vehicle" i], [class*="vin-result" i], [data-vehicle]').first();
  const _secVisible = (await _vehicleSec.count()) > 0 && (await _vehicleSec.isVisible().catch(() => false));
  console.log(`📋 VIN lookup check — readonly fields with values: ${_hasDetails}, vehicle section: ${_secVisible}`);
  assert.ok(_hasDetails || _secVisible, 'VIN lookup should populate vehicle details (expected readonly fields with values or a vehicle section to appear)');
});

When('the user selects {string} for {string}', async function (value, label) {
  const _ownLower = value.toLowerCase().trim();
  // 1. Try a <select> dropdown
  const _sel = this.page.locator('select[id*="own" i], select[name*="own" i], select[aria-label*="own" i], select[aria-label*="vehicle" i]').first();
  if ((await _sel.count()) > 0 && (await _sel.isVisible().catch(() => false))) {
    await _sel.selectOption({ label: value }).catch(async () => {
      const _opts = await _sel.locator('option').allTextContents();
      const _m = _opts.find(o => o.trim().toLowerCase().includes(_ownLower)) || _opts[1];
      if (_m) await _sel.selectOption({ label: _m.trim() }).catch(() => {});
    });
    console.log(`📋 Selected own vehicle (dropdown): "${value}"`);
  } else {
    // 2. Try clicking a label with the matching text (Yes / No)
    const _lbl = this.page.locator(`label:has-text("${value}")`).first();
    if ((await _lbl.count()) > 0) {
      await _lbl.click();
      console.log(`📋 Clicked label "${value}" for own vehicle`);
    } else {
      // 3. Try radio button by value attribute
      const _radio = this.page.locator(`input[type="radio"][value="${value}" i], input[type="radio"][value="${_ownLower}" i]`).first();
      if ((await _radio.count()) > 0) {
        await _radio.evaluate(el => el.click());
        console.log(`📋 Selected own vehicle (radio): "${value}"`);
      } else {
        console.log(`⚠️  Could not find selector for "${label}" = "${value}"`);
      }
    }
  }
  // Wait for contact details fields to reveal after the Yes/No selection, instead of a fixed timeout
  await this.page.waitForSelector(
    'input[name*="first" i], input[id*="first" i], input[name*="email" i], input[id*="email" i]',
    { state: 'visible', timeout: 8000 }
  ).catch(() => {});
});

When('the ownership contact details form is displayed', async function () {
  // The selects step already waits for the contact fields — just verify they're visible
  const _contactSel = [
    'input[name*="first" i], input[id*="first" i], input[aria-label*="first" i]',
    'input[name*="email" i], input[id*="email" i]',
    '[class*="contact" i] input, [id*="contact" i] input',
  ].join(', ');
  await this.page.waitForSelector(_contactSel, { timeout: 8000 }).catch(() => {
    console.log('⚠️  Contact details section may not have appeared — continuing');
  });
  console.log('📋 Contact details section check complete');
});

When('the user selects Title from the dropdown', async function (table) {
  const _rows = table.rowsHash();
  const _t = (_rows['Title'] || _rows['Value'] || 'Mr').toString();
  const _tSel = this.page.locator("select[name*='title' i], select[id*='title' i], select[name*='salut' i], input[name*='salut' i], input[id*='salut' i]").first();
  if ((await _tSel.count()) > 0) {
    const _tag = await _tSel.evaluate(el => el.tagName.toLowerCase());
    if (_tag === 'select') {
      await _tSel.selectOption({ label: _t }).catch(async () => {
        const _opts = await _tSel.locator('option').allTextContents();
        const _m = _opts.find(o => o.trim().toLowerCase().includes(_t.toLowerCase())) || _opts[1];
        if (_m) await _tSel.selectOption({ label: _m.trim() }).catch(() => {});
      });
    } else {
      await _tSel.fill(_t);
    }
    console.log(`📋 Selected Title: "${_t}"`);
  } else { console.log('⚠️  Title/Salutation field not found — skipping'); }
  await this.page.waitForTimeout(300);
});

When('the user enters First Name {string}', async function (value) {
  const _f = this.page.locator("input[name*='firstName' i], input[id*='first-name' i], input[name*='first-name' i], #cad-modal-first-name, input[placeholder*='first name' i], input[aria-label*='first name' i]").first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled First Name: "${value}"`);
  } else {
    await this.fillField('first name', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters Last Name {string}', async function (value) {
  const _f = this.page.locator("input[name*='lastName' i], input[id*='last-name' i], input[name*='last-name' i], #cad-modal-last-name, input[placeholder*='last name' i], input[aria-label*='last name' i]").first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Last Name: "${value}"`);
  } else {
    await this.fillField('last name', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters Email {string}', async function (value) {
  const _f = this.page.locator('input[type="email"], input[name*="email" i], input[id*="email" i], #cad-modal-email-address').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Email: "${value}"`);
  } else {
    await this.fillField('email', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters Mobile {string}', async function (value) {
  const _f = this.page.locator('input[type="tel"], input[name*="phone" i], input[name*="mobile" i], input[id*="phone" i], #cad-modal-phone-number').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Mobile: "${value}"`);
  } else {
    await this.fillField('phone', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters Address {string}', async function (value) {
  // Exclude email-type inputs — #cad-modal-email-address contains "address" in its ID
  // and would otherwise be matched before the real address field
  const _f = this.page.locator(
    'input[name*="street" i], input[id*="street" i],'
    + ' input[placeholder="Address"], input[placeholder="Address*"],'
    + ' input[aria-label="Address"], input[aria-label*="street address" i],'
    + ' input[name*="address" i]:not([type="email"]):not([id*="email" i]),'
    + ' input[id*="address" i]:not([type="email"]):not([id*="email" i])'
  ).first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Address: "${value}"`);
  } else {
    await this.fillField('address', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user enters Suburb {string}', async function (value) {
  const _f = this.page.locator('input[name*="suburb" i], input[id*="suburb" i], input[name*="city" i], input[placeholder*="suburb" i], input[aria-label*="suburb" i]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Suburb: "${value}"`);
  } else {
    await this.fillField('suburb', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user selects State from the dropdown', async function (table) {
  const _rows = table.rowsHash();
  const _want = (_rows['State'] || _rows['Value'] || '').toString();
  const _dd = this.page.locator('select[name*="state" i], select[id*="state" i], select[aria-label*="state" i], select[name*="province" i]').first();
  if ((await _dd.count()) > 0) {
    await _dd.scrollIntoViewIfNeeded().catch(() => {});
    if (_want) {
      await _dd.selectOption({ label: _want }).catch(async () => {
        const _opts = await _dd.locator('option').allTextContents();
        const _m = _opts.find(o => o.trim().toLowerCase().includes(_want.toLowerCase()));
        if (_m) await _dd.selectOption({ label: _m.trim() }).catch(() => {});
      });
    }
    console.log(`📋 Selected State: "${await _dd.inputValue().catch(() => '')}"`);
  } else { console.log('⚠️  State dropdown not found'); }
  await this.page.waitForTimeout(500);
});

When('the user enters Postcode {string}', async function (value) {
  const _f = this.page.locator('input[name*="postcode" i], input[id*="postcode" i], input[name*="postal" i], input[id*="postal" i], input[placeholder*="postcode" i]').first();
  if ((await _f.count()) > 0) {
    await _f.waitFor({ state: 'visible', timeout: 10000 });
    await _f.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await _f.clear().catch(() => {});
    await _f.fill(value);
    console.log(`📋 Filled Postcode: "${value}"`);
  } else {
    await this.fillField('postcode', value);
  }
  await this.page.waitForTimeout(300);
});

When('the user checks the marketing consent checkbox {string}', async function (param) {
  const _cb = this.page.locator('input[type="checkbox"][name*="marketing" i], input[type="checkbox"][name*="newsletter" i], input[type="checkbox"][id*="marketing" i]').first();
  if ((await _cb.count()) > 0) {
    const _checked = await _cb.isChecked().catch(() => false);
    if (_checked !== true) {
      const _lbl = _cb.locator('xpath=ancestor::label[1]').first();
      if ((await _lbl.count()) > 0) {
        await _lbl.click({ force: true, timeout: 3000 }).catch(async () => {
          await _cb.evaluate(el => el.click()).catch(() => {});
        });
      } else { await _cb.evaluate(el => el.click()).catch(() => {}); }
    }
    console.log('📋 Marketing Authorisation: true');
  } else { console.log('⚠️  Marketing Authorisation checkbox not found — skipping'); }
});

Then('the ownership update should be submitted successfully', async function () {
  // Wait for network to settle after popup submission
  await this.page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  await this.page.waitForTimeout(2000);

  const _url = this.page.url();
  let _found = false;
  let _foundEl = null;

  // Look for a visible thank-you / success heading or message
  // Use h1/h2/h3 and dedicated success/confirmation containers
  const _candidates = this.page.locator([
    '[class*="thank"]', '[id*="thank"]',
    '[class*="success"]', '[id*="success"]',
    '[class*="confirmation-message"]',
    'h1', 'h2', 'h3',
  ].join(', '));

  const _count = await _candidates.count();
  for (let i = 0; i < _count && !_found; i++) {
    const _el = _candidates.nth(i);
    const _vis = await _el.isVisible().catch(() => false);
    if (!_vis) continue;
    const _txt = (await _el.textContent().catch(() => '')).toLowerCase().trim();
    // Skip the confirmation popup header (it's asking to confirm, not success)
    if (_txt.includes('please confirm you are the owner')) continue;
    // Must match a positive submission outcome — not generic page text
    if (/thank you|successfully updated|your details.*updated|update.*confirmed/i.test(_txt)) {
      _found = true; _foundEl = _el;
    }
  }

  // Scroll to success message if found
  if (_foundEl) {
    await _foundEl.evaluate(el => el.scrollIntoView({ behavior: 'smooth', block: 'center' })).catch(() => {});
    await this.page.waitForTimeout(800);
  }

  console.log(`📋 Submission result — url: ${_url}, success element found: ${_found}`);
  this.successMessage = { displayed: _found, text: _found ? 'Ownership update submitted successfully' : '' };
  assert.ok(_found, `Ownership form should be submitted successfully — no thank-you message detected. URL: ${_url}`);
});

When('the user confirms ownership in the popup', async function () {
  // DOM confirmed (2026-04): the confirmation modal is a .tingle-modal.hyu-modal.tiny whose
  // visibility is toggled via inline style (display:none removed) — NOT a CSS class.
  // The Submit button inside is <button class="btn"> with NO type="submit".
  const _modalSel  = '.tingle-modal.hyu-modal.tiny .modal-box';
  const _btnSel    = '.tingle-modal.hyu-modal.tiny .modal-box button.btn';

  // Wait for the modal-box to become visible (inline style removed by JS)
  const _appeared = await this.page.waitForSelector(_modalSel, { state: 'visible', timeout: 60000 })
    .then(() => true)
    .catch(() => { console.log('ℹ️  Confirmation popup did not appear — may have submitted directly'); return false; });

  if (_appeared) {
    console.log('📋 Confirmation popup visible — clicking Submit button');
    await this.page.click(_btnSel, { force: true, timeout: 10000 });
    console.log('📋 Popup Submit clicked');

    // Wait for the modal to disappear (inline style display:none restored)
    await this.page.waitForSelector(_modalSel, { state: 'hidden', timeout: 30000 })
      .catch(() => { console.log('⚠️  Modal still visible after click — continuing'); });

    // The actual ownership API call fires after popup confirm — wait for network to settle
    await this.page.waitForLoadState('networkidle', { timeout: 60000 })
      .catch(async () => { console.log('ℹ️  networkidle not reached — waiting 5s'); await this.page.waitForTimeout(5000); });
    await this.page.waitForTimeout(2000);
    console.log('📋 Post-popup network settled. URL:', this.page.url());
  }
});

