// @protected
/**
 * Auto-Generated Step Definitions for: Form submission on Hyundai Pip Page
 * Source: pipFIFO.feature
 * Generated: 2026-04-22T06:08:30.476Z
 * Target URL: https://stage.hyundai.com.au/au/en/cars/suvs/kona
 *
 * DOM Field Map:
 *   "Model*" → #test-drive-modal-model-pcm2
 *   "First Name*" → #cad-modal-first-name
 *   "Last Name*" → #cad-modal-last-name
 *   "Email Address*" → #cad-modal-email-address
 *   "Phone Number*" → #cad-modal-phone-number
 *   "Postcode*" → #cad-modal-postcode
 *   "When are you likely to purchase?" → #cad-modal-purchase-time
 *   "Model*" → #cad-modal-model-pcm2
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('I am a user on the Hyundai Pip Page', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: I am a user on the Hyundai Pip Page`);
  assert.ok(content.length > 0, 'I am a user on the Hyundai Pip Page');
});

Given('the user navigates to Pip Page', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: pip
  const _pageKeys = ["pip"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan — only when no exact match and key is non-empty
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en/cars/suvs/kona';
  console.log(`📋 Navigating to pip: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

Given('user clicks on Buying Tools', async function () {
  console.log('📋 Clicking Buying Tools button to open sticky menu');

  // The sticky bar at the bottom of the Pip page has a "Buying tools" hamburger button
  // that opens a drawer/dropdown with options like Test Drive, Contact a Dealer, etc.
  const btn = this.page.locator([
    'button:has-text("Buying tools")',
    'button:has-text("Buying Tools")',
    '[class*="buying-tools"] button',
    '[class*="buyingtools"] button',
    '[class*="sticky"] button:has-text("Buying")',
    '[class*="pip-sticky"] button',
    '.hyu-sticky-nav button',
    '.pip-cta button:has-text("Buying")',
    '[data-label*="buying" i]',
  ].join(', ')).first();

  await btn.waitFor({ state: 'visible', timeout: 15000 });
  await btn.scrollIntoViewIfNeeded().catch(() => {});
  await this.page.waitForTimeout(500);
  await btn.click();
  await this.page.waitForTimeout(1500); // wait for menu/drawer to open
  console.log('✅ Clicked Buying Tools — menu should now be open');
});

Given('user selects Test Drive', async function () {
  console.log('📋 Selecting Test Drive from the Buying Tools menu');

  // Allow the Buying Tools drawer to fully open before searching for links.
  await this.page.waitForTimeout(1000);

  // The Hyundai PIP page main nav contains nav-card / dxo-selector-submenu-card
  // elements with "Book a test drive" text — these are NOT the Buying Tools drawer
  // items. We must find the link inside the sticky buying-tools drawer specifically,
  // and never click a nav-card or an element inside the primary navbar.
  const element = await this.page.evaluateHandle(() => {
    const isVisible = (el) => {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return false;
      const s = getComputedStyle(el);
      return s.display !== 'none' && s.visibility !== 'hidden' && s.opacity !== '0';
    };

    const pattern = /test\s*drive|book\s*a\s*test\s*drive/i;
    const candidates = Array.from(document.querySelectorAll('a, button')).filter(el => {
      if (!pattern.test(el.textContent)) return false;
      if (!isVisible(el)) return false;
      // Exclude nav-card / submenu-card elements (main navbar dropdown links)
      if (/nav-card|submenu-card|submenu/i.test(el.className)) return false;
      // Exclude anything sitting inside the primary navigation
      if (el.closest('.navbar-menu, .primary-nav, [class*="navbar-menu"], [class*="primary-nav"]')) return false;
      return true;
    });
    return candidates[0] ?? null;
  });

  const el = element.asElement();
  if (!el) throw new Error('Could not find the Test Drive link in the Buying Tools drawer');

  await el.scrollIntoViewIfNeeded().catch(() => {});
  await this.page.waitForTimeout(300);

  try {
    await el.click({ timeout: 10000 });
  } catch {
    // The drawer link may still have a z-index overlay; dispatch a native click.
    await el.dispatchEvent('click');
  }

  this._activeModalHeader = 'Book a test drive';
  await this.page.waitForTimeout(1500);
  console.log('✅ Clicked Test Drive — BATD modal should now be opening');
});

Given('the user selects Powertrain from test data and clicks Next', async function () {
  // The loading step may find the generic "Test Drive" sheet before the specific
  // "Test Drive FIFO PCM2" sheet. Look for the FIFO-specific sheet first in allConfluenceData.
  const allData = this.allConfluenceData || {};
  const fifoKey = Object.keys(allData).find(k => /test drive fifo pcm2/i.test(k));
  const fifoRow = fifoKey ? (allData[fifoKey]?.[0] || {}) : {};
  const d = Object.keys(fifoRow).length ? fifoRow : (this.testDriveData?.[0] || {});

  // Confluence column header is "Powetrain" (typo — one 'r' missing); check both spellings
  const powertrain = d.Powertrain || d.Powetrain  ||
                     d.powertrain || d.powetrain  ||
                     d.Variant    || d.variant    || '';
  const postcode   = d['Your Location'] || d.Postcode || d.postcode || d['Set Location'] || '2000';

  console.log(`📋 testDriveData keys: [${Object.keys(d).join(', ')}]`);

  if (!powertrain) {
    throw new Error(`No Powertrain/Powetrain/Variant key found in test data — available keys: [${Object.keys(d).join(', ')}]`);
  }
  console.log(`📋 Powertrain: "${powertrain}", Postcode: "${postcode}"`);

  // Scope to the active BATD modal
  const header = this._activeModalHeader || 'Book a test drive';
  const modal = this.page.locator('.modal-wrapper').filter({
    has: this.page.locator(`.modal-header:has-text("${header}")`)
  }).first();

  // ── Step A: Wait for ModelOfinterest__c options to load (async, ~3-4s after modal opens) ──
  await this.page.locator('#test-drive-modal-model-pcm2 option').first()
    .waitFor({ state: 'attached', timeout: 15000 }).catch(() => {});

  // Dispatch change on model select to trigger FuelType__c options loading
  await this.page.evaluate(() => {
    const sel = document.querySelector('#test-drive-modal-model-pcm2');
    if (sel) sel.dispatchEvent(new Event('change', { bubbles: true }));
  });
  await this.page.waitForTimeout(1000);

  // ── Step B: Wait for FuelType__c options, then select the matching powertrain ──
  await this.page.locator('#test-drive-modal-energy-type-pcm2 option').first()
    .waitFor({ state: 'attached', timeout: 10000 }).catch(() => {});

  const energySelect = this.page.locator('#test-drive-modal-energy-type-pcm2');
  const energyOpts = await energySelect.locator('option').allTextContents().catch(() => []);
  console.log(`  Energy type options: [${energyOpts.join(', ')}]`);

  if (energyOpts.length > 0) {
    const match = energyOpts.find(o => o.trim().toLowerCase().includes(powertrain.toLowerCase()));
    if (match) {
      await energySelect.selectOption({ label: match.trim() });
      console.log(`✅ Selected powertrain: "${match.trim()}"`);
    } else {
      // Default to Petrol if test data value doesn't match any option
      const petrol = energyOpts.find(o => /petrol/i.test(o));
      const fallback = petrol || energyOpts.find(o => o.trim() && !/select|choose|--/i.test(o));
      if (fallback) await energySelect.selectOption({ label: fallback.trim() });
      console.log(`⚠️ "${powertrain}" not in [${energyOpts.join(', ')}] — selected "${fallback}"`);
    }
  }

  // ── Step C: Click Next → moves to "Set your location" step ──
  const nextBtn = modal.locator('button:has-text("Next"), button.next').first();
  await nextBtn.waitFor({ state: 'visible', timeout: 10000 });
  await nextBtn.click();
  await this.page.waitForTimeout(2000);

  // ── Step D: Handle "Set your location" step so Next becomes enabled ──
  // After clicking Next from the model/powertrain step, the modal shows "Set your location."
  // with a "Set location" button. Click it and fill the postcode so the Next button enables.
  // The actual Next click to advance to personal details is done by "the user clicks Next".
  const setLocationBtn = this.page.locator(
    'div[role="button"]:has-text("Set location"), button:has-text("Set location"), a:has-text("Set location")'
  ).first();

  if ((await setLocationBtn.count()) > 0 && await setLocationBtn.isVisible().catch(() => false)) {
    console.log(`📍 "Set your location" step detected — setting postcode: ${postcode}`);
    await setLocationBtn.scrollIntoViewIfNeeded().catch(() => {});
    await setLocationBtn.click({ timeout: 5000 });
    await this.page.waitForTimeout(1500);
    const { handleLocationModal } = await import('./commonHelpers.js');
    await handleLocationModal(this.page, postcode);
    await this.page.waitForTimeout(1000);
    console.log(`✅ Location set — Next button should now be enabled`);
  }

  console.log('✅ Model/Powertrain step complete — "the user clicks Next" will advance to personal details');
});

Given('user selects on Contact a dealer', async function () {
  console.log('📋 Selecting Contact a Dealer from the Buying Tools menu');

  // After the Buying Tools menu opens, click the "Contact a dealer" link
  const link = this.page.locator([
    '[class*="buying-tools"] a:has-text("Contact a dealer")',
    '[class*="buying-tools"] a:has-text("Contact a Dealer")',
    '[class*="buying-tools"] button:has-text("Contact a dealer")',
    '[class*="buying-tools"] button:has-text("Contact a Dealer")',
    '[class*="buyingtools"] a:has-text("Contact")',
    '[class*="sticky"] a:has-text("Contact a dealer")',
    '[class*="sticky"] button:has-text("Contact a dealer")',
    'a:has-text("Contact a dealer")',
    'button:has-text("Contact a dealer")',
  ].join(', ')).first();

  await link.waitFor({ state: 'visible', timeout: 10000 });
  await link.click();
  this._activeModalHeader = 'Contact a dealer';
  await this.page.waitForTimeout(1500); // wait for modal to start opening
  console.log('✅ Clicked Contact a Dealer — CAD modal should now be opening');
});

When('the user selects Powertrain from test data', async function () {
  console.log('📋 Selecting Powertrain from test data (CAD scenario)');
  // Check contactDealerData first (FAD CAD scenario sets this to PCM2 data with a Powertrain column),
  // then fall back to testDriveData. Never use Variant as a powertrain fallback — that picks the
  // wrong value (e.g. "KONA Elite") from unrelated FIFO test data.
  const d = this.contactDealerData?.[0] || this.testDriveData?.[0] || {};
  const powertrain = d.Powertrain || d.Powetrain ||
                     d.powertrain || d.powetrain || '';

  if (!powertrain) {
    console.log('⚠️ No Powertrain/Powetrain in test data — skipping');
    return;
  }

  console.log(`📋 Powertrain from test data: "${powertrain}"`);

  // Scope to the active CAD modal
  const header = this._activeModalHeader || 'Contact a dealer';
  const modal = this.page.locator('.modal-wrapper').filter({
    has: this.page.locator(`.modal-header:has-text("${header}")`)
  }).first();

  // In the CAD form the powertrain/energy-type dropdown appears 2-3s AFTER model selection.
  // Use the same selectors as CPC_allFIFOs_auto.steps.js (line 415):
  const dropdown = modal.locator([
    '#cad-page-energy-type',
    'select[name="FuelType__c"]',
    'select[id*="energy" i]',
    'select[id*="powertrain" i]',
    'select[id*="fuel" i]',
  ].join(', ')).first();

  const visible = await dropdown.waitFor({ state: 'visible', timeout: 5000 }).then(() => true).catch(() => false);
  if (visible) {
    await dropdown.scrollIntoViewIfNeeded().catch(() => {});
    const options = await dropdown.locator('option').allTextContents();
    console.log(`  Powertrain dropdown options: [${options.join(', ')}]`);
    const match = options.find(o => o.trim().toLowerCase().includes(powertrain.toLowerCase()));
    if (match) {
      await dropdown.selectOption({ label: match.trim() });
      console.log(`✅ Selected powertrain: "${match.trim()}"`);
    } else if (options.length > 1) {
      const fallback = options.find(o => o.trim() && !/select|choose|--/i.test(o));
      if (fallback) {
        await dropdown.selectOption({ label: fallback.trim() });
        console.log(`⚠️ "${powertrain}" not found — selected fallback "${fallback}"`);
      }
    }
  } else {
    console.log(`ℹ️  Powertrain dropdown did not appear after model selection — skipping`);
  }
});
