/**
 * Auto-Generated Step Definitions for: Hyundai homepage Contact Us flow
 * Source: test.feature
 * Generated: 2026-04-29T03:50:13.635Z
 * Target URL: https://stage.hyundai.com.au/au/en
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user has loaded the test data from the Confluence page', async function () {
  // Test data is loaded in the Before hook from Confluence
  assert.ok(this.allConfluenceData || (this.testData && this.testData.length > 0),
    'Test data should be loaded from Confluence');
});

Given('the user is on the Hyundai Home page', async function () {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  // pageKey variants: hyundai home
  const _pageKeys = ["hyundai home"];
  let url = '';
  if (this.pageUrls) {
    for (const _k of _pageKeys) {
      if (this.pageUrls[_k]) { url = this.pageUrls[_k]; break; }
    }
    if (!url) {
      // Fuzzy scan against keys
      const _entry = _pageKeys.length && Object.entries(this.pageUrls).find(([k]) =>
        _pageKeys.some(pk => pk && (k.includes(pk) || pk.includes(k))));
      if (_entry) url = _entry[1];
    }
    if (!url) {
      // Slug scan against URL paths — handles "customer care" → ".../customer-care/..."
      const _slugEntry = Object.entries(this.pageUrls).find(([, u]) => {
        try {
          const _p = new URL(u).pathname.toLowerCase();
          return _pageKeys.some(pk => pk && (_p.includes(pk.replace(/\s+/g, '-')) || _p.includes(pk.replace(/\s+/g, ''))));
        } catch { return false; }
      });
      if (_slugEntry) url = _slugEntry[1];
    }
  }
  url = url || 'https://stage.hyundai.com.au/au/en';
  console.log(`📋 Navigating to hyundai home: ${url}`);
  if (url) {
    await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  } else {
    await this.page.waitForLoadState('domcontentloaded');
  }
  await this.page.waitForTimeout(2000);
});

When('the user clicks on Contact us in footer', async function () {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks (scoped to <footer>)
  await this.clickButton('Contact us', { section: 'footer' });
  await this.page.waitForTimeout(2000);
});

Then('the Customer Care page is displayed', async function () {
  await this.page.waitForLoadState('domcontentloaded');
  await this.page.waitForTimeout(1500);
  const _pageName = "Customer Care";
  const _curUrl = this.page.url();
  let _ok = (await this.page.content()).length > 500;
  // If we know the page name, verify the URL contains a slug derived from it
  // OR the page heading/title contains the name.
  if (_ok && _pageName) {
    const _slug = _pageName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const _firstWord = _pageName.toLowerCase().split(/\s+/)[0];
    const _urlOk = _curUrl.toLowerCase().includes(_slug) || _curUrl.toLowerCase().includes(_firstWord);
    if (!_urlOk) {
      // URL doesn't match — fall back to checking visible heading text
      const _re = new RegExp(_pageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      const _headingMatch = await this.page.locator('h1, h2').filter({ hasText: _re }).first().isVisible().catch(() => false);
      const _titleMatch = _re.test(await this.page.title().catch(() => ''));
      _ok = _headingMatch || _titleMatch;
      if (!_ok) console.warn(`⚠️  Page "${_pageName}" expected — current URL is ${_curUrl}`);
    }
  }
  assert.ok(_ok, `Page "${_pageName || 'expected'}" should be displayed (current URL: ${_curUrl})`);
});

When('the user clicks on Contact us', async function () {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks
  await this.clickButton('Contact us');
  await this.page.waitForTimeout(2000);
});

Then('the Contact Us page is displayed', async function () {
  await this.page.waitForLoadState('domcontentloaded');
  await this.page.waitForTimeout(1500);
  const _pageName = "Contact Us";
  const _curUrl = this.page.url();
  let _ok = (await this.page.content()).length > 500;
  // If we know the page name, verify the URL contains a slug derived from it
  // OR the page heading/title contains the name.
  if (_ok && _pageName) {
    const _slug = _pageName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const _firstWord = _pageName.toLowerCase().split(/\s+/)[0];
    const _urlOk = _curUrl.toLowerCase().includes(_slug) || _curUrl.toLowerCase().includes(_firstWord);
    if (!_urlOk) {
      // URL doesn't match — fall back to checking visible heading text
      const _re = new RegExp(_pageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      const _headingMatch = await this.page.locator('h1, h2').filter({ hasText: _re }).first().isVisible().catch(() => false);
      const _titleMatch = _re.test(await this.page.title().catch(() => ''));
      _ok = _headingMatch || _titleMatch;
      if (!_ok) console.warn(`⚠️  Page "${_pageName}" expected — current URL is ${_curUrl}`);
    }
  }
  assert.ok(_ok, `Page "${_pageName || 'expected'}" should be displayed (current URL: ${_curUrl})`);
});
