/**
 * Auto-Generated Step Definitions for: Model Variant Carousel Navigation Performance
 * Source: ticket3650.feature
 * Generated: 2026-05-12T06:40:19.189Z
 * Target URL: (resolved at runtime)
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { authenticatePim } from '../../../utils/pimAuth.js';

// Resolve a feature-file argument to a real URL.
// Accepts either a literal URL ("https://...") or a named page from the
// Confluence "Environment URLs" sheet (cached in .cache/activeEnvironment.json
// by scripts/agentOrchestrator.js).
function resolveNamedUrl(arg) {
  if (/^https?:\/\//i.test(arg)) return arg;
  try {
    const cachePath = path.resolve('.cache', 'activeEnvironment.json');
    if (!fs.existsSync(cachePath)) return arg;
    const env = JSON.parse(fs.readFileSync(cachePath, 'utf-8'));
    const map = env.pageUrls || {};
    const key = arg.toLowerCase().trim();
    if (map[key]) return map[key];
    // tolerant match: any page whose name contains the arg or vice versa
    const hit = Object.entries(map).find(([k]) => k.includes(key) || key.includes(k));
    if (hit && hit[1]) return hit[1];
  } catch { /* ignore */ }
  return arg;
}

Given('user navigates to {string}', async function (target) {
  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }

  const url = resolveNamedUrl(target);
  if (url !== target) {
    console.log(`📋 Resolved "${target}" → ${url}`);
  }
  if (!/^https?:\/\//i.test(url)) {
    throw new Error(`Could not resolve "${target}" to a URL. Add it to the "Environment URLs" sheet in Confluence, or pass a full https:// URL.`);
  }

  // ─── PIM site: authenticate before navigating ───
  if (/stage-pim\.hyundai\.com\.au|pim\.hyundai\.com\.au/i.test(url)) {
    console.log('🔐 PIM URL detected — authenticating via /api/authenticate...');
    // Decide which company to pick from the page name (defaults to Hyundai).
    const company = /genesis/i.test(target) ? 'Genesis' : 'Hyundai';
    await authenticatePim(this, { company });
    console.log(`✅ PIM authenticated and "${company}" selected`);
    return;
  }

  console.log(`📋 Navigating to: ${url}`);
  await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('user clicks on the {string} variant tab', async function (param) {
  // Variant tabs on Hyundai model pages render as <li class="tab">LABEL</li>
  // inside <ul class="tabs">. Generic clickButton() matches the first <a>/<button>
  // whose text *contains* the label (substring), which can land on a marketing
  // card or hero link instead of the carousel tab. Target the tab element
  // directly with EXACT text first; fall back to a role=tab; finally fall back
  // to the generic helper.
  const exactCandidates = [
    this.page.locator('ul.tabs li.tab').filter({ hasText: new RegExp(`^\\s*${param.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}\\s*$`, 'i') }).first(),
    this.page.locator('[class*="tab" i]').filter({ has: this.page.locator(`text="${param}"`) }).first(),
    this.page.getByRole('tab', { name: param, exact: true }),
    this.page.locator('li.tab', { hasText: param }).first(),
  ];

  let clicked = false;
  for (const cand of exactCandidates) {
    const count = await cand.count().catch(() => 0);
    if (count === 0) continue;
    const visible = await cand.first().isVisible().catch(() => false);
    if (!visible) continue;
    await cand.first().scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    await cand.first().click({ timeout: 5000 }).catch(async () => {
      await cand.first().click({ force: true, timeout: 5000 }).catch(async () => {
        await cand.first().evaluate(el => el.click());
      });
    });
    console.log(`📋 Clicked variant tab "${param}" via exact-tab match`);
    clicked = true;
    break;
  }

  if (!clicked) {
    console.log(`⚠️  Exact tab not found for "${param}" — falling back to generic clickButton`);
    await this.clickButton(param);
  }
  await this.page.waitForTimeout(1500);
});

Then('the target page should load successfully', async function () {
  await this.page.waitForTimeout(3000);
  // Multi-signal success check: visible thank-you/success element, success-bearing URL,
  // success text on page, OR a 2xx form-submission API response captured by network listener.
  const success = this.page.locator('[class*="thank"], [class*="success"], [class*="confirm"], [class*="all-done"], [class*="complete"]').first();
  const visible = (await success.count()) > 0 && (await success.isVisible().catch(() => false));
  const url = this.page.url();
  const urlOk = /thank|success|confirm|complete/i.test(url);
  const textOk = await this.page.getByText(/thank you|thank-you|we.?ll be in touch|received your enquiry|enquiry submitted|submitted successfully|we have received/i).first().isVisible().catch(() => false);
  const apiOk = Array.isArray(this.networkResponses) && this.networkResponses.some(r =>
    r && r.status >= 200 && r.status < 300 && /\/form\/|\blead|\benquir|\bcontact|\bsubmit/i.test(r.url || ''));
  console.log(`📋 Success check — visibleEl=${visible} urlOk=${urlOk} textOk=${textOk} apiOk=${apiOk}`);
  assert.ok(visible || urlOk || textOk || apiOk, 'the target page should load successfully');
  this.successMessage = { displayed: true };
});

// NOTE: The following steps are now implemented as reusable common steps in
// common_steps.js:
//   - "the current URL should not contain {string}"
//   - "the page response time should be less than {int} ms"
//   - "no renderer long task longer than {int} ms should occur"
